/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Thu Jun 15 20:47:38 PDT 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbCFFunctional_h__
#define __mkTbCFFunctional_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbCFFunctional module */
class MOD_mkTbCFFunctional : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_fifo_data_0;
  MOD_Reg<tUInt8> INST_fifo_data_1;
  MOD_Reg<tUInt8> INST_fifo_deqReq_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_deqReq_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqReq_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo_deqReq_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_deqReq_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo_deqReq_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqReq_wires_1;
  MOD_Reg<tUInt8> INST_fifo_empty;
  MOD_Reg<tUInt32> INST_fifo_enqReq_ehrReg;
  MOD_Wire<tUInt32> INST_fifo_enqReq_ignored_wires_0;
  MOD_Wire<tUInt32> INST_fifo_enqReq_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo_enqReq_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_enqReq_virtual_reg_1;
  MOD_Wire<tUInt32> INST_fifo_enqReq_wires_0;
  MOD_Wire<tUInt32> INST_fifo_enqReq_wires_1;
  MOD_Reg<tUInt8> INST_fifo_full;
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt32> INST_m_input_count;
  MOD_Reg<tUInt32> INST_m_output_count;
  MOD_Wire<tUInt8> INST_m_randomA_ignore;
  MOD_Reg<tUInt8> INST_m_randomA_initialized;
  MOD_Wire<tUInt8> INST_m_randomA_zaz;
  MOD_Wire<tUInt8> INST_m_randomB_ignore;
  MOD_Reg<tUInt8> INST_m_randomB_initialized;
  MOD_Wire<tUInt8> INST_m_randomB_zaz;
  MOD_Wire<tUInt8> INST_m_randomC_ignore;
  MOD_Reg<tUInt8> INST_m_randomC_initialized;
  MOD_Wire<tUInt8> INST_m_randomC_zaz;
  MOD_Wire<tUInt8> INST_m_randomData_ignore;
  MOD_Reg<tUInt8> INST_m_randomData_initialized;
  MOD_Wire<tUInt8> INST_m_randomData_zaz;
  MOD_Fifo<tUInt8> INST_m_ref_fifo;
 
 /* Constructor */
 public:
  MOD_mkTbCFFunctional(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_WILL_FIRE_RL_m_stop_tb;
  tUInt8 DEF_CAN_FIRE_RL_m_stop_tb;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_WILL_FIRE_RL_m_check_outputs;
  tUInt8 DEF_CAN_FIRE_RL_m_check_outputs;
  tUInt8 DEF_WILL_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_CAN_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_WILL_FIRE_RL_m_init;
  tUInt8 DEF_CAN_FIRE_RL_m_init;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_fifo_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize;
  tUInt8 DEF_fifo_empty__h3110;
  tUInt8 DEF_fifo_full__h3124;
  tUInt32 DEF_x__h6070;
  tUInt32 DEF_x__h6218;
  tUInt8 DEF_x_wget__h4091;
  tUInt8 DEF_x_wget__h3702;
  tUInt8 DEF_v__h3839;
  tUInt8 DEF_v__h4228;
  tUInt8 DEF_m_input_count_03_EQ_1024___d136;
  tUInt8 DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111;
  tUInt8 DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97;
  tUInt8 DEF_NOT_fifo_empty_5___d63;
  tUInt8 DEF_NOT_fifo_full_9___d58;
 
 /* Local definitions */
 private:
  tUInt8 DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9;
  tUInt8 DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28;
  tUInt32 DEF_v__h4925;
  tUInt32 DEF_v__h4535;
  tUInt32 DEF_v__h4148;
  tUInt32 DEF_v__h3759;
  tUInt32 DEF_x__h5820;
  tUInt32 DEF_fifo_enqReq_wires_0_wget____d5;
  tUInt32 DEF_fifo_enqReq_ehrReg___d7;
  tUInt8 DEF_y__h6005;
  tUInt8 DEF_x_wget__h4868;
  tUInt8 DEF_x__h6004;
  tUInt8 DEF_fifo_deqReq_wires_0_whas____d25;
  tUInt8 DEF_fifo_deqReq_wires_0_wget____d26;
  tUInt8 DEF_fifo_deqReq_ehrReg__h1971;
  tUInt8 DEF_fifo_enqReq_wires_0_whas____d4;
  tUInt8 DEF_x__h1151;
  tUInt8 DEF_x__h1152;
  tUInt8 DEF_fifo_enqReq_ehrReg_BIT_8___d8;
  tUInt8 DEF_fifo_enqReq_wires_0_wget_BIT_8___d6;
  tUInt8 DEF_v__h5005;
  tUInt8 DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19;
 
 /* Rules */
 public:
  void RL_fifo_enqReq_canonicalize();
  void RL_fifo_deqReq_canonicalize();
  void RL_fifo_canonicalize();
  void RL_m_randomA_every();
  void RL_m_randomA_every_1();
  void RL_m_randomB_every();
  void RL_m_randomB_every_1();
  void RL_m_randomC_every();
  void RL_m_randomC_every_1();
  void RL_m_randomData_every();
  void RL_m_randomData_every_1();
  void RL_m_init();
  void RL_m_feed_inputs();
  void RL_m_check_outputs();
  void RL_m_check_fifos_not_full();
  void RL_m_check_fifos_not_empty();
  void RL_m_check_fifos_first();
  void RL_m_stop_tb();
  void RL_m_cycle_inc();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbCFFunctional &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbCFFunctional &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbCFFunctional &backing);
};

#endif /* ifndef __mkTbCFFunctional_h__ */
