/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sat Jun 10 08:58:51 PDT 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbBypassScheduling.h"


/* Constructor */
MOD_mkTbBypassScheduling::MOD_mkTbBypassScheduling(tSimStateHdl simHdl,
						   char const *name,
						   Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_m_fifo_1_data(simHdl, "m_fifo_1_data", this, 8u),
    INST_m_fifo_1_ehr_ehrReg(simHdl, "m_fifo_1_ehr_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ignored_wires_0(simHdl, "m_fifo_1_ehr_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ignored_wires_1(simHdl, "m_fifo_1_ehr_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_ignored_wires_2(simHdl, "m_fifo_1_ehr_ignored_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_virtual_reg_0(simHdl, "m_fifo_1_ehr_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_ehr_virtual_reg_1(simHdl, "m_fifo_1_ehr_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_ehr_virtual_reg_2(simHdl, "m_fifo_1_ehr_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_ehr_wires_0(simHdl, "m_fifo_1_ehr_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_wires_1(simHdl, "m_fifo_1_ehr_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_ehr_wires_2(simHdl, "m_fifo_1_ehr_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_1_empty_ehrReg(simHdl, "m_fifo_1_empty_ehrReg", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_m_fifo_1_empty_ignored_wires_0(simHdl, "m_fifo_1_empty_ignored_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_empty_ignored_wires_1(simHdl, "m_fifo_1_empty_ignored_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_empty_virtual_reg_0(simHdl, "m_fifo_1_empty_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_empty_virtual_reg_1(simHdl, "m_fifo_1_empty_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_empty_wires_0(simHdl, "m_fifo_1_empty_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_empty_wires_1(simHdl, "m_fifo_1_empty_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_full_ehrReg(simHdl, "m_fifo_1_full_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_1_full_ignored_wires_0(simHdl, "m_fifo_1_full_ignored_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_full_ignored_wires_1(simHdl, "m_fifo_1_full_ignored_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_full_virtual_reg_0(simHdl, "m_fifo_1_full_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_full_virtual_reg_1(simHdl, "m_fifo_1_full_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_full_wires_0(simHdl, "m_fifo_1_full_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_1_full_wires_1(simHdl, "m_fifo_1_full_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_data(simHdl, "m_fifo_2_data", this, 8u),
    INST_m_fifo_2_ehr_ehrReg(simHdl, "m_fifo_2_ehr_ehrReg", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ignored_wires_0(simHdl, "m_fifo_2_ehr_ignored_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ignored_wires_1(simHdl, "m_fifo_2_ehr_ignored_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_ignored_wires_2(simHdl, "m_fifo_2_ehr_ignored_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_virtual_reg_0(simHdl, "m_fifo_2_ehr_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_ehr_virtual_reg_1(simHdl, "m_fifo_2_ehr_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_ehr_virtual_reg_2(simHdl, "m_fifo_2_ehr_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_ehr_wires_0(simHdl, "m_fifo_2_ehr_wires_0", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_wires_1(simHdl, "m_fifo_2_ehr_wires_1", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_ehr_wires_2(simHdl, "m_fifo_2_ehr_wires_2", this, 2u, (tUInt8)0u),
    INST_m_fifo_2_empty_ehrReg(simHdl, "m_fifo_2_empty_ehrReg", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_m_fifo_2_empty_ignored_wires_0(simHdl, "m_fifo_2_empty_ignored_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_empty_ignored_wires_1(simHdl, "m_fifo_2_empty_ignored_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_empty_virtual_reg_0(simHdl, "m_fifo_2_empty_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_empty_virtual_reg_1(simHdl, "m_fifo_2_empty_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_empty_wires_0(simHdl, "m_fifo_2_empty_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_empty_wires_1(simHdl, "m_fifo_2_empty_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_full_ehrReg(simHdl, "m_fifo_2_full_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_fifo_2_full_ignored_wires_0(simHdl, "m_fifo_2_full_ignored_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_full_ignored_wires_1(simHdl, "m_fifo_2_full_ignored_wires_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_full_virtual_reg_0(simHdl, "m_fifo_2_full_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_full_virtual_reg_1(simHdl, "m_fifo_2_full_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_full_wires_0(simHdl, "m_fifo_2_full_wires_0", this, 1u, (tUInt8)0u),
    INST_m_fifo_2_full_wires_1(simHdl, "m_fifo_2_full_wires_1", this, 1u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 74u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbBypassScheduling::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_RL_m_deq_fifo_1", SYM_DEF, &DEF_CAN_FIRE_RL_m_deq_fifo_1, 1u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_m_enq_fifo_1", SYM_DEF, &DEF_CAN_FIRE_RL_m_enq_fifo_1, 1u);
  init_symbol(&symbols[2u],
	      "CAN_FIRE_RL_m_fifo_1_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_m_fifo_1_empty_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_m_fifo_1_full_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_m_fifo_2_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_m_fifo_2_empty_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_m_fifo_2_full_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize,
	      1u);
  init_symbol(&symbols[8u], "m_fifo_1_data", SYM_MODULE, &INST_m_fifo_1_data);
  init_symbol(&symbols[9u], "m_fifo_1_ehr_ehrReg", SYM_MODULE, &INST_m_fifo_1_ehr_ehrReg);
  init_symbol(&symbols[10u],
	      "m_fifo_1_ehr_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_ignored_wires_0);
  init_symbol(&symbols[11u],
	      "m_fifo_1_ehr_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_ignored_wires_1);
  init_symbol(&symbols[12u],
	      "m_fifo_1_ehr_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_ignored_wires_2);
  init_symbol(&symbols[13u],
	      "m_fifo_1_ehr_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_virtual_reg_0);
  init_symbol(&symbols[14u],
	      "m_fifo_1_ehr_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_virtual_reg_1);
  init_symbol(&symbols[15u],
	      "m_fifo_1_ehr_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_1_ehr_virtual_reg_2);
  init_symbol(&symbols[16u], "m_fifo_1_ehr_wires_0", SYM_MODULE, &INST_m_fifo_1_ehr_wires_0);
  init_symbol(&symbols[17u], "m_fifo_1_ehr_wires_1", SYM_MODULE, &INST_m_fifo_1_ehr_wires_1);
  init_symbol(&symbols[18u], "m_fifo_1_ehr_wires_2", SYM_MODULE, &INST_m_fifo_1_ehr_wires_2);
  init_symbol(&symbols[19u], "m_fifo_1_empty_ehrReg", SYM_MODULE, &INST_m_fifo_1_empty_ehrReg);
  init_symbol(&symbols[20u],
	      "m_fifo_1_empty_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_empty_ignored_wires_0);
  init_symbol(&symbols[21u],
	      "m_fifo_1_empty_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_empty_ignored_wires_1);
  init_symbol(&symbols[22u],
	      "m_fifo_1_empty_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_empty_virtual_reg_0);
  init_symbol(&symbols[23u],
	      "m_fifo_1_empty_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_empty_virtual_reg_1);
  init_symbol(&symbols[24u], "m_fifo_1_empty_wires_0", SYM_MODULE, &INST_m_fifo_1_empty_wires_0);
  init_symbol(&symbols[25u], "m_fifo_1_empty_wires_1", SYM_MODULE, &INST_m_fifo_1_empty_wires_1);
  init_symbol(&symbols[26u], "m_fifo_1_full_ehrReg", SYM_MODULE, &INST_m_fifo_1_full_ehrReg);
  init_symbol(&symbols[27u],
	      "m_fifo_1_full_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_full_ignored_wires_0);
  init_symbol(&symbols[28u],
	      "m_fifo_1_full_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_full_ignored_wires_1);
  init_symbol(&symbols[29u],
	      "m_fifo_1_full_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_1_full_virtual_reg_0);
  init_symbol(&symbols[30u],
	      "m_fifo_1_full_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_1_full_virtual_reg_1);
  init_symbol(&symbols[31u], "m_fifo_1_full_wires_0", SYM_MODULE, &INST_m_fifo_1_full_wires_0);
  init_symbol(&symbols[32u], "m_fifo_1_full_wires_1", SYM_MODULE, &INST_m_fifo_1_full_wires_1);
  init_symbol(&symbols[33u], "m_fifo_2_data", SYM_MODULE, &INST_m_fifo_2_data);
  init_symbol(&symbols[34u], "m_fifo_2_ehr_ehrReg", SYM_MODULE, &INST_m_fifo_2_ehr_ehrReg);
  init_symbol(&symbols[35u],
	      "m_fifo_2_ehr_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_ignored_wires_0);
  init_symbol(&symbols[36u],
	      "m_fifo_2_ehr_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_ignored_wires_1);
  init_symbol(&symbols[37u],
	      "m_fifo_2_ehr_ignored_wires_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_ignored_wires_2);
  init_symbol(&symbols[38u],
	      "m_fifo_2_ehr_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_virtual_reg_0);
  init_symbol(&symbols[39u],
	      "m_fifo_2_ehr_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_virtual_reg_1);
  init_symbol(&symbols[40u],
	      "m_fifo_2_ehr_virtual_reg_2",
	      SYM_MODULE,
	      &INST_m_fifo_2_ehr_virtual_reg_2);
  init_symbol(&symbols[41u], "m_fifo_2_ehr_wires_0", SYM_MODULE, &INST_m_fifo_2_ehr_wires_0);
  init_symbol(&symbols[42u], "m_fifo_2_ehr_wires_1", SYM_MODULE, &INST_m_fifo_2_ehr_wires_1);
  init_symbol(&symbols[43u], "m_fifo_2_ehr_wires_2", SYM_MODULE, &INST_m_fifo_2_ehr_wires_2);
  init_symbol(&symbols[44u], "m_fifo_2_empty_ehrReg", SYM_MODULE, &INST_m_fifo_2_empty_ehrReg);
  init_symbol(&symbols[45u],
	      "m_fifo_2_empty_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_empty_ignored_wires_0);
  init_symbol(&symbols[46u],
	      "m_fifo_2_empty_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_empty_ignored_wires_1);
  init_symbol(&symbols[47u],
	      "m_fifo_2_empty_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_empty_virtual_reg_0);
  init_symbol(&symbols[48u],
	      "m_fifo_2_empty_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_empty_virtual_reg_1);
  init_symbol(&symbols[49u], "m_fifo_2_empty_wires_0", SYM_MODULE, &INST_m_fifo_2_empty_wires_0);
  init_symbol(&symbols[50u], "m_fifo_2_empty_wires_1", SYM_MODULE, &INST_m_fifo_2_empty_wires_1);
  init_symbol(&symbols[51u], "m_fifo_2_full_ehrReg", SYM_MODULE, &INST_m_fifo_2_full_ehrReg);
  init_symbol(&symbols[52u],
	      "m_fifo_2_full_ignored_wires_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_full_ignored_wires_0);
  init_symbol(&symbols[53u],
	      "m_fifo_2_full_ignored_wires_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_full_ignored_wires_1);
  init_symbol(&symbols[54u],
	      "m_fifo_2_full_virtual_reg_0",
	      SYM_MODULE,
	      &INST_m_fifo_2_full_virtual_reg_0);
  init_symbol(&symbols[55u],
	      "m_fifo_2_full_virtual_reg_1",
	      SYM_MODULE,
	      &INST_m_fifo_2_full_virtual_reg_1);
  init_symbol(&symbols[56u], "m_fifo_2_full_wires_0", SYM_MODULE, &INST_m_fifo_2_full_wires_0);
  init_symbol(&symbols[57u], "m_fifo_2_full_wires_1", SYM_MODULE, &INST_m_fifo_2_full_wires_1);
  init_symbol(&symbols[58u], "RL_m_deq_fifo_1", SYM_RULE);
  init_symbol(&symbols[59u], "RL_m_enq_fifo_1", SYM_RULE);
  init_symbol(&symbols[60u], "RL_m_fifo_1_ehr_canonicalize", SYM_RULE);
  init_symbol(&symbols[61u], "RL_m_fifo_1_empty_canonicalize", SYM_RULE);
  init_symbol(&symbols[62u], "RL_m_fifo_1_full_canonicalize", SYM_RULE);
  init_symbol(&symbols[63u], "RL_m_fifo_2_ehr_canonicalize", SYM_RULE);
  init_symbol(&symbols[64u], "RL_m_fifo_2_empty_canonicalize", SYM_RULE);
  init_symbol(&symbols[65u], "RL_m_fifo_2_full_canonicalize", SYM_RULE);
  init_symbol(&symbols[66u],
	      "WILL_FIRE_RL_m_deq_fifo_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_deq_fifo_1,
	      1u);
  init_symbol(&symbols[67u],
	      "WILL_FIRE_RL_m_enq_fifo_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_enq_fifo_1,
	      1u);
  init_symbol(&symbols[68u],
	      "WILL_FIRE_RL_m_fifo_1_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[69u],
	      "WILL_FIRE_RL_m_fifo_1_empty_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize,
	      1u);
  init_symbol(&symbols[70u],
	      "WILL_FIRE_RL_m_fifo_1_full_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize,
	      1u);
  init_symbol(&symbols[71u],
	      "WILL_FIRE_RL_m_fifo_2_ehr_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize,
	      1u);
  init_symbol(&symbols[72u],
	      "WILL_FIRE_RL_m_fifo_2_empty_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize,
	      1u);
  init_symbol(&symbols[73u],
	      "WILL_FIRE_RL_m_fifo_2_full_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize,
	      1u);
}


/* Rule actions */

void MOD_mkTbBypassScheduling::RL_m_fifo_1_empty_canonicalize()
{
  tUInt8 DEF_IF_m_fifo_1_empty_wires_1_whas_THEN_m_fifo_1_e_ETC___d7;
  DEF_m_fifo_1_empty_wires_0_whas____d3 = INST_m_fifo_1_empty_wires_0.METH_whas();
  DEF_m_fifo_1_empty_wires_0_wget____d4 = INST_m_fifo_1_empty_wires_0.METH_wget();
  DEF_m_fifo_1_empty_ehrReg__h7315 = INST_m_fifo_1_empty_ehrReg.METH_read();
  DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6 = DEF_m_fifo_1_empty_wires_0_whas____d3 ? DEF_m_fifo_1_empty_wires_0_wget____d4 : DEF_m_fifo_1_empty_ehrReg__h7315;
  DEF_IF_m_fifo_1_empty_wires_1_whas_THEN_m_fifo_1_e_ETC___d7 = INST_m_fifo_1_empty_wires_1.METH_whas() ? INST_m_fifo_1_empty_wires_1.METH_wget() : DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6;
  INST_m_fifo_1_empty_ehrReg.METH_write(DEF_IF_m_fifo_1_empty_wires_1_whas_THEN_m_fifo_1_e_ETC___d7);
}

void MOD_mkTbBypassScheduling::RL_m_fifo_1_full_canonicalize()
{
  tUInt8 DEF_IF_m_fifo_1_full_wires_1_whas_THEN_m_fifo_1_fu_ETC___d14;
  DEF_m_fifo_1_full_ehrReg__h1681 = INST_m_fifo_1_full_ehrReg.METH_read();
  DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13 = INST_m_fifo_1_full_wires_0.METH_whas() ? INST_m_fifo_1_full_wires_0.METH_wget() : DEF_m_fifo_1_full_ehrReg__h1681;
  DEF_IF_m_fifo_1_full_wires_1_whas_THEN_m_fifo_1_fu_ETC___d14 = INST_m_fifo_1_full_wires_1.METH_whas() ? INST_m_fifo_1_full_wires_1.METH_wget() : DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13;
  INST_m_fifo_1_full_ehrReg.METH_write(DEF_IF_m_fifo_1_full_wires_1_whas_THEN_m_fifo_1_fu_ETC___d14);
}

void MOD_mkTbBypassScheduling::RL_m_fifo_2_empty_canonicalize()
{
  tUInt8 DEF_IF_m_fifo_2_empty_wires_1_whas__5_THEN_m_fifo__ETC___d21;
  tUInt8 DEF_m_fifo_2_empty_ehrReg__h2543;
  DEF_m_fifo_2_empty_ehrReg__h2543 = INST_m_fifo_2_empty_ehrReg.METH_read();
  DEF_IF_m_fifo_2_empty_wires_1_whas__5_THEN_m_fifo__ETC___d21 = INST_m_fifo_2_empty_wires_1.METH_whas() ? INST_m_fifo_2_empty_wires_1.METH_wget() : (INST_m_fifo_2_empty_wires_0.METH_whas() ? INST_m_fifo_2_empty_wires_0.METH_wget() : DEF_m_fifo_2_empty_ehrReg__h2543);
  INST_m_fifo_2_empty_ehrReg.METH_write(DEF_IF_m_fifo_2_empty_wires_1_whas__5_THEN_m_fifo__ETC___d21);
}

void MOD_mkTbBypassScheduling::RL_m_fifo_2_full_canonicalize()
{
  tUInt8 DEF_IF_m_fifo_2_full_wires_1_whas__2_THEN_m_fifo_2_ETC___d28;
  tUInt8 DEF_m_fifo_2_full_ehrReg__h3379;
  DEF_m_fifo_2_full_ehrReg__h3379 = INST_m_fifo_2_full_ehrReg.METH_read();
  DEF_IF_m_fifo_2_full_wires_1_whas__2_THEN_m_fifo_2_ETC___d28 = INST_m_fifo_2_full_wires_1.METH_whas() ? INST_m_fifo_2_full_wires_1.METH_wget() : (INST_m_fifo_2_full_wires_0.METH_whas() ? INST_m_fifo_2_full_wires_0.METH_wget() : DEF_m_fifo_2_full_ehrReg__h3379);
  INST_m_fifo_2_full_ehrReg.METH_write(DEF_IF_m_fifo_2_full_wires_1_whas__2_THEN_m_fifo_2_ETC___d28);
}

void MOD_mkTbBypassScheduling::RL_m_fifo_1_ehr_canonicalize()
{
  tUInt8 DEF_def__h4337;
  tUInt8 DEF_x__h4303;
  DEF_def__h7746 = INST_m_fifo_1_ehr_ehrReg.METH_read();
  DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36 = INST_m_fifo_1_ehr_wires_0.METH_whas() ? INST_m_fifo_1_ehr_wires_0.METH_wget() : DEF_def__h7746;
  DEF_def__h4337 = INST_m_fifo_1_ehr_wires_1.METH_whas() ? INST_m_fifo_1_ehr_wires_1.METH_wget() : DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36;
  DEF_x__h4303 = INST_m_fifo_1_ehr_wires_2.METH_whas() ? INST_m_fifo_1_ehr_wires_2.METH_wget() : DEF_def__h4337;
  INST_m_fifo_1_ehr_ehrReg.METH_write(DEF_x__h4303);
}

void MOD_mkTbBypassScheduling::RL_m_fifo_2_ehr_canonicalize()
{
  tUInt8 DEF_def__h5555;
  tUInt8 DEF_def__h5437;
  tUInt8 DEF_x__h5403;
  tUInt8 DEF_def__h5573;
  DEF_def__h5573 = INST_m_fifo_2_ehr_ehrReg.METH_read();
  DEF_def__h5555 = INST_m_fifo_2_ehr_wires_0.METH_whas() ? INST_m_fifo_2_ehr_wires_0.METH_wget() : DEF_def__h5573;
  DEF_def__h5437 = INST_m_fifo_2_ehr_wires_1.METH_whas() ? INST_m_fifo_2_ehr_wires_1.METH_wget() : DEF_def__h5555;
  DEF_x__h5403 = INST_m_fifo_2_ehr_wires_2.METH_whas() ? INST_m_fifo_2_ehr_wires_2.METH_wget() : DEF_def__h5437;
  INST_m_fifo_2_ehr_ehrReg.METH_write(DEF_x__h5403);
}

void MOD_mkTbBypassScheduling::RL_m_enq_fifo_1()
{
  tUInt8 DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61;
  tUInt8 DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d55;
  tUInt8 DEF_x__h5681;
  DEF_def__h7746 = INST_m_fifo_1_ehr_ehrReg.METH_read();
  DEF_m_fifo_1_ehr_virtual_reg_2_read____d49 = INST_m_fifo_1_ehr_virtual_reg_2.METH_read();
  DEF_m_fifo_1_ehr_virtual_reg_1_read____d50 = INST_m_fifo_1_ehr_virtual_reg_1.METH_read();
  DEF_x__h5681 = DEF_m_fifo_1_ehr_virtual_reg_2_read____d49 || (DEF_m_fifo_1_ehr_virtual_reg_1_read____d50 || INST_m_fifo_1_ehr_virtual_reg_0.METH_read()) ? (tUInt8)0u : DEF_def__h7746;
  DEF_m_fifo_1_full_ehrReg__h1681 = INST_m_fifo_1_full_ehrReg.METH_read();
  DEF_m_fifo_1_empty_ehrReg__h7315 = INST_m_fifo_1_empty_ehrReg.METH_read();
  DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d55 = DEF_x__h5681 == (tUInt8)0u;
  DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61 = DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d55 && (INST_m_fifo_1_full_virtual_reg_1.METH_read() || (INST_m_fifo_1_full_virtual_reg_0.METH_read() || !DEF_m_fifo_1_full_ehrReg__h1681));
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_full_wires_0.METH_wset((tUInt8)1u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_full_ignored_wires_0.METH_wset(DEF_m_fifo_1_full_ehrReg__h1681);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_full_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_empty_wires_0.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_empty_ignored_wires_0.METH_wset(DEF_m_fifo_1_empty_ehrReg__h7315);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_empty_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d61)
    INST_m_fifo_1_data.METH_write((tUInt8)1u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d55)
    INST_m_fifo_1_ehr_wires_0.METH_wset((tUInt8)1u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d55)
    INST_m_fifo_1_ehr_ignored_wires_0.METH_wset(DEF_def__h7746);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d55)
    INST_m_fifo_1_ehr_virtual_reg_0.METH_write((tUInt8)0u);
}

void MOD_mkTbBypassScheduling::RL_m_deq_fifo_1()
{
  tUInt8 DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70;
  tUInt8 DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d64;
  tUInt8 DEF_x__h7088;
  DEF_def__h7746 = INST_m_fifo_1_ehr_ehrReg.METH_read();
  DEF_m_fifo_1_ehr_virtual_reg_2_read____d49 = INST_m_fifo_1_ehr_virtual_reg_2.METH_read();
  DEF_m_fifo_1_ehr_virtual_reg_1_read____d50 = INST_m_fifo_1_ehr_virtual_reg_1.METH_read();
  DEF_m_fifo_1_empty_wires_0_whas____d3 = INST_m_fifo_1_empty_wires_0.METH_whas();
  DEF_m_fifo_1_full_ehrReg__h1681 = INST_m_fifo_1_full_ehrReg.METH_read();
  DEF_m_fifo_1_empty_wires_0_wget____d4 = INST_m_fifo_1_empty_wires_0.METH_wget();
  DEF_m_fifo_1_empty_ehrReg__h7315 = INST_m_fifo_1_empty_ehrReg.METH_read();
  DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36 = INST_m_fifo_1_ehr_wires_0.METH_whas() ? INST_m_fifo_1_ehr_wires_0.METH_wget() : DEF_def__h7746;
  DEF_x__h7088 = DEF_m_fifo_1_ehr_virtual_reg_2_read____d49 || DEF_m_fifo_1_ehr_virtual_reg_1_read____d50 ? (tUInt8)0u : DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36;
  DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13 = INST_m_fifo_1_full_wires_0.METH_whas() ? INST_m_fifo_1_full_wires_0.METH_wget() : DEF_m_fifo_1_full_ehrReg__h1681;
  DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6 = DEF_m_fifo_1_empty_wires_0_whas____d3 ? DEF_m_fifo_1_empty_wires_0_wget____d4 : DEF_m_fifo_1_empty_ehrReg__h7315;
  DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d64 = DEF_x__h7088 == (tUInt8)1u;
  DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70 = DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d64 && (INST_m_fifo_1_empty_virtual_reg_1.METH_read() || (DEF_m_fifo_1_empty_wires_0_whas____d3 ? !DEF_m_fifo_1_empty_wires_0_wget____d4 : !DEF_m_fifo_1_empty_ehrReg__h7315));
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70)
    INST_m_fifo_1_empty_wires_1.METH_wset((tUInt8)1u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70)
    INST_m_fifo_1_empty_ignored_wires_1.METH_wset(DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70)
    INST_m_fifo_1_empty_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70)
    INST_m_fifo_1_full_wires_1.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70)
    INST_m_fifo_1_full_ignored_wires_1.METH_wset(DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d70)
    INST_m_fifo_1_full_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d64)
    INST_m_fifo_1_ehr_wires_1.METH_wset((tUInt8)0u);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d64)
    INST_m_fifo_1_ehr_ignored_wires_1.METH_wset(DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36);
  if (DEF_IF_m_fifo_1_ehr_virtual_reg_2_read__9_OR_m_fif_ETC___d64)
    INST_m_fifo_1_ehr_virtual_reg_1.METH_write((tUInt8)0u);
}


/* Methods */


/* Reset routines */

void MOD_mkTbBypassScheduling::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_m_fifo_2_full_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_2_empty_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_2_ehr_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_full_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_empty_ehrReg.reset_RST(ARG_rst_in);
  INST_m_fifo_1_ehr_ehrReg.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbBypassScheduling::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbBypassScheduling::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_m_fifo_1_data.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_ehr_wires_2.dump_state(indent + 2u);
  INST_m_fifo_1_empty_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_empty_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_empty_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_empty_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_empty_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_empty_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_empty_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_full_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_1_full_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_full_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_1_full_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_1_full_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_1_full_wires_0.dump_state(indent + 2u);
  INST_m_fifo_1_full_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_data.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_ignored_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_virtual_reg_2.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_ehr_wires_2.dump_state(indent + 2u);
  INST_m_fifo_2_empty_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_empty_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_empty_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_empty_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_empty_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_empty_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_empty_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_full_ehrReg.dump_state(indent + 2u);
  INST_m_fifo_2_full_ignored_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_full_ignored_wires_1.dump_state(indent + 2u);
  INST_m_fifo_2_full_virtual_reg_0.dump_state(indent + 2u);
  INST_m_fifo_2_full_virtual_reg_1.dump_state(indent + 2u);
  INST_m_fifo_2_full_wires_0.dump_state(indent + 2u);
  INST_m_fifo_2_full_wires_1.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbBypassScheduling::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 77u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_deq_fifo_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_enq_fifo_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_empty_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_1_full_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_empty_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_fifo_2_full_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_deq_fifo_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_enq_fifo_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_empty_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_1_full_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_ehr_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_empty_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_fifo_2_full_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "def__h7746", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_1_ehr_virtual_reg_1_read____d50", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_1_ehr_virtual_reg_2_read____d49", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_1_empty_ehrReg__h7315", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_1_empty_wires_0_wget____d4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_1_empty_wires_0_whas____d3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_fifo_1_full_ehrReg__h1681", 1u);
  num = INST_m_fifo_1_data.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_ehr_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_empty_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_1_full_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_data.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_ignored_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_virtual_reg_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_ehr_wires_2.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_empty_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_ehrReg.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_ignored_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_ignored_wires_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_virtual_reg_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_virtual_reg_1.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_wires_0.dump_VCD_defs(num);
  num = INST_m_fifo_2_full_wires_1.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbBypassScheduling::dump_VCD(tVCDDumpType dt,
					unsigned int levels,
					MOD_mkTbBypassScheduling &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbBypassScheduling::vcd_defs(tVCDDumpType dt, MOD_mkTbBypassScheduling &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_m_deq_fifo_1) != DEF_CAN_FIRE_RL_m_deq_fifo_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_deq_fifo_1, 1u);
	backing.DEF_CAN_FIRE_RL_m_deq_fifo_1 = DEF_CAN_FIRE_RL_m_deq_fifo_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_enq_fifo_1) != DEF_CAN_FIRE_RL_m_enq_fifo_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_enq_fifo_1, 1u);
	backing.DEF_CAN_FIRE_RL_m_enq_fifo_1 = DEF_CAN_FIRE_RL_m_enq_fifo_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize) != DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36) != DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36, 2u);
	backing.DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36 = DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6) != DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6, 1u);
	backing.DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6 = DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6;
      }
      ++num;
      if ((backing.DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13) != DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13, 1u);
	backing.DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13 = DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_deq_fifo_1) != DEF_WILL_FIRE_RL_m_deq_fifo_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_deq_fifo_1, 1u);
	backing.DEF_WILL_FIRE_RL_m_deq_fifo_1 = DEF_WILL_FIRE_RL_m_deq_fifo_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_enq_fifo_1) != DEF_WILL_FIRE_RL_m_enq_fifo_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_enq_fifo_1, 1u);
	backing.DEF_WILL_FIRE_RL_m_enq_fifo_1 = DEF_WILL_FIRE_RL_m_enq_fifo_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize) != DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize;
      }
      ++num;
      if ((backing.DEF_def__h7746) != DEF_def__h7746)
      {
	vcd_write_val(sim_hdl, num, DEF_def__h7746, 2u);
	backing.DEF_def__h7746 = DEF_def__h7746;
      }
      ++num;
      if ((backing.DEF_m_fifo_1_ehr_virtual_reg_1_read____d50) != DEF_m_fifo_1_ehr_virtual_reg_1_read____d50)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_1_ehr_virtual_reg_1_read____d50, 1u);
	backing.DEF_m_fifo_1_ehr_virtual_reg_1_read____d50 = DEF_m_fifo_1_ehr_virtual_reg_1_read____d50;
      }
      ++num;
      if ((backing.DEF_m_fifo_1_ehr_virtual_reg_2_read____d49) != DEF_m_fifo_1_ehr_virtual_reg_2_read____d49)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_1_ehr_virtual_reg_2_read____d49, 1u);
	backing.DEF_m_fifo_1_ehr_virtual_reg_2_read____d49 = DEF_m_fifo_1_ehr_virtual_reg_2_read____d49;
      }
      ++num;
      if ((backing.DEF_m_fifo_1_empty_ehrReg__h7315) != DEF_m_fifo_1_empty_ehrReg__h7315)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_1_empty_ehrReg__h7315, 1u);
	backing.DEF_m_fifo_1_empty_ehrReg__h7315 = DEF_m_fifo_1_empty_ehrReg__h7315;
      }
      ++num;
      if ((backing.DEF_m_fifo_1_empty_wires_0_wget____d4) != DEF_m_fifo_1_empty_wires_0_wget____d4)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_1_empty_wires_0_wget____d4, 1u);
	backing.DEF_m_fifo_1_empty_wires_0_wget____d4 = DEF_m_fifo_1_empty_wires_0_wget____d4;
      }
      ++num;
      if ((backing.DEF_m_fifo_1_empty_wires_0_whas____d3) != DEF_m_fifo_1_empty_wires_0_whas____d3)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_1_empty_wires_0_whas____d3, 1u);
	backing.DEF_m_fifo_1_empty_wires_0_whas____d3 = DEF_m_fifo_1_empty_wires_0_whas____d3;
      }
      ++num;
      if ((backing.DEF_m_fifo_1_full_ehrReg__h1681) != DEF_m_fifo_1_full_ehrReg__h1681)
      {
	vcd_write_val(sim_hdl, num, DEF_m_fifo_1_full_ehrReg__h1681, 1u);
	backing.DEF_m_fifo_1_full_ehrReg__h1681 = DEF_m_fifo_1_full_ehrReg__h1681;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_deq_fifo_1, 1u);
      backing.DEF_CAN_FIRE_RL_m_deq_fifo_1 = DEF_CAN_FIRE_RL_m_deq_fifo_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_enq_fifo_1, 1u);
      backing.DEF_CAN_FIRE_RL_m_enq_fifo_1 = DEF_CAN_FIRE_RL_m_enq_fifo_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_empty_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize = DEF_CAN_FIRE_RL_m_fifo_1_full_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_empty_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize = DEF_CAN_FIRE_RL_m_fifo_2_full_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36, 2u);
      backing.DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36 = DEF_IF_m_fifo_1_ehr_wires_0_whas__3_THEN_m_fifo_1__ETC___d36;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6, 1u);
      backing.DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6 = DEF_IF_m_fifo_1_empty_wires_0_whas_THEN_m_fifo_1_e_ETC___d6;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13, 1u);
      backing.DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13 = DEF_IF_m_fifo_1_full_wires_0_whas__0_THEN_m_fifo_1_ETC___d13;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_deq_fifo_1, 1u);
      backing.DEF_WILL_FIRE_RL_m_deq_fifo_1 = DEF_WILL_FIRE_RL_m_deq_fifo_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_enq_fifo_1, 1u);
      backing.DEF_WILL_FIRE_RL_m_enq_fifo_1 = DEF_WILL_FIRE_RL_m_enq_fifo_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_empty_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize = DEF_WILL_FIRE_RL_m_fifo_1_full_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_ehr_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_empty_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize = DEF_WILL_FIRE_RL_m_fifo_2_full_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_def__h7746, 2u);
      backing.DEF_def__h7746 = DEF_def__h7746;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_1_ehr_virtual_reg_1_read____d50, 1u);
      backing.DEF_m_fifo_1_ehr_virtual_reg_1_read____d50 = DEF_m_fifo_1_ehr_virtual_reg_1_read____d50;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_1_ehr_virtual_reg_2_read____d49, 1u);
      backing.DEF_m_fifo_1_ehr_virtual_reg_2_read____d49 = DEF_m_fifo_1_ehr_virtual_reg_2_read____d49;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_1_empty_ehrReg__h7315, 1u);
      backing.DEF_m_fifo_1_empty_ehrReg__h7315 = DEF_m_fifo_1_empty_ehrReg__h7315;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_1_empty_wires_0_wget____d4, 1u);
      backing.DEF_m_fifo_1_empty_wires_0_wget____d4 = DEF_m_fifo_1_empty_wires_0_wget____d4;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_1_empty_wires_0_whas____d3, 1u);
      backing.DEF_m_fifo_1_empty_wires_0_whas____d3 = DEF_m_fifo_1_empty_wires_0_whas____d3;
      vcd_write_val(sim_hdl, num++, DEF_m_fifo_1_full_ehrReg__h1681, 1u);
      backing.DEF_m_fifo_1_full_ehrReg__h1681 = DEF_m_fifo_1_full_ehrReg__h1681;
    }
}

void MOD_mkTbBypassScheduling::vcd_prims(tVCDDumpType dt, MOD_mkTbBypassScheduling &backing)
{
  INST_m_fifo_1_data.dump_VCD(dt, backing.INST_m_fifo_1_data);
  INST_m_fifo_1_ehr_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ehrReg);
  INST_m_fifo_1_ehr_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ignored_wires_0);
  INST_m_fifo_1_ehr_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ignored_wires_1);
  INST_m_fifo_1_ehr_ignored_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_ehr_ignored_wires_2);
  INST_m_fifo_1_ehr_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_ehr_virtual_reg_0);
  INST_m_fifo_1_ehr_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_ehr_virtual_reg_1);
  INST_m_fifo_1_ehr_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_1_ehr_virtual_reg_2);
  INST_m_fifo_1_ehr_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_ehr_wires_0);
  INST_m_fifo_1_ehr_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_ehr_wires_1);
  INST_m_fifo_1_ehr_wires_2.dump_VCD(dt, backing.INST_m_fifo_1_ehr_wires_2);
  INST_m_fifo_1_empty_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_empty_ehrReg);
  INST_m_fifo_1_empty_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_empty_ignored_wires_0);
  INST_m_fifo_1_empty_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_empty_ignored_wires_1);
  INST_m_fifo_1_empty_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_empty_virtual_reg_0);
  INST_m_fifo_1_empty_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_empty_virtual_reg_1);
  INST_m_fifo_1_empty_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_empty_wires_0);
  INST_m_fifo_1_empty_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_empty_wires_1);
  INST_m_fifo_1_full_ehrReg.dump_VCD(dt, backing.INST_m_fifo_1_full_ehrReg);
  INST_m_fifo_1_full_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_full_ignored_wires_0);
  INST_m_fifo_1_full_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_full_ignored_wires_1);
  INST_m_fifo_1_full_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_1_full_virtual_reg_0);
  INST_m_fifo_1_full_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_1_full_virtual_reg_1);
  INST_m_fifo_1_full_wires_0.dump_VCD(dt, backing.INST_m_fifo_1_full_wires_0);
  INST_m_fifo_1_full_wires_1.dump_VCD(dt, backing.INST_m_fifo_1_full_wires_1);
  INST_m_fifo_2_data.dump_VCD(dt, backing.INST_m_fifo_2_data);
  INST_m_fifo_2_ehr_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ehrReg);
  INST_m_fifo_2_ehr_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ignored_wires_0);
  INST_m_fifo_2_ehr_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ignored_wires_1);
  INST_m_fifo_2_ehr_ignored_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_ehr_ignored_wires_2);
  INST_m_fifo_2_ehr_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_ehr_virtual_reg_0);
  INST_m_fifo_2_ehr_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_ehr_virtual_reg_1);
  INST_m_fifo_2_ehr_virtual_reg_2.dump_VCD(dt, backing.INST_m_fifo_2_ehr_virtual_reg_2);
  INST_m_fifo_2_ehr_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_ehr_wires_0);
  INST_m_fifo_2_ehr_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_ehr_wires_1);
  INST_m_fifo_2_ehr_wires_2.dump_VCD(dt, backing.INST_m_fifo_2_ehr_wires_2);
  INST_m_fifo_2_empty_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_empty_ehrReg);
  INST_m_fifo_2_empty_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_empty_ignored_wires_0);
  INST_m_fifo_2_empty_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_empty_ignored_wires_1);
  INST_m_fifo_2_empty_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_empty_virtual_reg_0);
  INST_m_fifo_2_empty_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_empty_virtual_reg_1);
  INST_m_fifo_2_empty_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_empty_wires_0);
  INST_m_fifo_2_empty_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_empty_wires_1);
  INST_m_fifo_2_full_ehrReg.dump_VCD(dt, backing.INST_m_fifo_2_full_ehrReg);
  INST_m_fifo_2_full_ignored_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_full_ignored_wires_0);
  INST_m_fifo_2_full_ignored_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_full_ignored_wires_1);
  INST_m_fifo_2_full_virtual_reg_0.dump_VCD(dt, backing.INST_m_fifo_2_full_virtual_reg_0);
  INST_m_fifo_2_full_virtual_reg_1.dump_VCD(dt, backing.INST_m_fifo_2_full_virtual_reg_1);
  INST_m_fifo_2_full_wires_0.dump_VCD(dt, backing.INST_m_fifo_2_full_wires_0);
  INST_m_fifo_2_full_wires_1.dump_VCD(dt, backing.INST_m_fifo_2_full_wires_1);
}
