/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Thu Jun 15 20:47:38 PDT 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkTbCFFunctional.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_9("\tERROR: Reached maximum cycle count!", 36u);
static std::string const __str_literal_1("\tERROR: should have dequeued %0d", 32u);
static std::string const __str_literal_4("\tERROR: test fifo is empty but reference fifo is not.",
					 53u);
static std::string const __str_literal_2("\tERROR: test fifo is full but reference fifo is not.",
					 52u);
static std::string const __str_literal_5("\tERROR: test fifo is not empty but reference fifo is.",
					 53u);
static std::string const __str_literal_3("\tERROR: test fifo is not full but reference fifo is.",
					 52u);
static std::string const __str_literal_6("\tError: fifo.first = %0d but ref_fifo.first = %0d.",
					 50u);
static std::string const __str_literal_7("\tFinished Test, PASS", 20u);
static std::string const __str_literal_8("\tOutput count = %0d", 19u);


/* Constructor */
MOD_mkTbCFFunctional::MOD_mkTbCFFunctional(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_fifo_data_0(simHdl, "fifo_data_0", this, 8u),
    INST_fifo_data_1(simHdl, "fifo_data_1", this, 8u),
    INST_fifo_deqReq_ehrReg(simHdl, "fifo_deqReq_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_fifo_deqReq_ignored_wires_0(simHdl, "fifo_deqReq_ignored_wires_0", this, 1u, (tUInt8)0u),
    INST_fifo_deqReq_ignored_wires_1(simHdl, "fifo_deqReq_ignored_wires_1", this, 1u, (tUInt8)0u),
    INST_fifo_deqReq_virtual_reg_0(simHdl, "fifo_deqReq_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_fifo_deqReq_virtual_reg_1(simHdl, "fifo_deqReq_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_fifo_deqReq_wires_0(simHdl, "fifo_deqReq_wires_0", this, 1u, (tUInt8)0u),
    INST_fifo_deqReq_wires_1(simHdl, "fifo_deqReq_wires_1", this, 1u, (tUInt8)0u),
    INST_fifo_empty(simHdl, "fifo_empty", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_fifo_enqReq_ehrReg(simHdl, "fifo_enqReq_ehrReg", this, 9u, 170u, (tUInt8)0u),
    INST_fifo_enqReq_ignored_wires_0(simHdl, "fifo_enqReq_ignored_wires_0", this, 9u, (tUInt8)0u),
    INST_fifo_enqReq_ignored_wires_1(simHdl, "fifo_enqReq_ignored_wires_1", this, 9u, (tUInt8)0u),
    INST_fifo_enqReq_virtual_reg_0(simHdl, "fifo_enqReq_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_fifo_enqReq_virtual_reg_1(simHdl, "fifo_enqReq_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_fifo_enqReq_wires_0(simHdl, "fifo_enqReq_wires_0", this, 9u, (tUInt8)0u),
    INST_fifo_enqReq_wires_1(simHdl, "fifo_enqReq_wires_1", this, 9u, (tUInt8)0u),
    INST_fifo_full(simHdl, "fifo_full", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_cycle(simHdl, "m_cycle", this, 32u, 0u, (tUInt8)0u),
    INST_m_input_count(simHdl, "m_input_count", this, 32u, 0u, (tUInt8)0u),
    INST_m_output_count(simHdl, "m_output_count", this, 32u, 0u, (tUInt8)0u),
    INST_m_randomA_ignore(simHdl, "m_randomA_ignore", this, 2u, (tUInt8)0u),
    INST_m_randomA_initialized(simHdl, "m_randomA_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_randomA_zaz(simHdl, "m_randomA_zaz", this, 2u, (tUInt8)0u),
    INST_m_randomB_ignore(simHdl, "m_randomB_ignore", this, 2u, (tUInt8)0u),
    INST_m_randomB_initialized(simHdl, "m_randomB_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_randomB_zaz(simHdl, "m_randomB_zaz", this, 2u, (tUInt8)0u),
    INST_m_randomC_ignore(simHdl, "m_randomC_ignore", this, 4u, (tUInt8)0u),
    INST_m_randomC_initialized(simHdl, "m_randomC_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_randomC_zaz(simHdl, "m_randomC_zaz", this, 4u, (tUInt8)0u),
    INST_m_randomData_ignore(simHdl, "m_randomData_ignore", this, 8u, (tUInt8)0u),
    INST_m_randomData_initialized(simHdl, "m_randomData_initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_randomData_zaz(simHdl, "m_randomData_zaz", this, 8u, (tUInt8)0u),
    INST_m_ref_fifo(simHdl, "m_ref_fifo", this, 8u, 2u, 1u, 0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h4925(2863311530u),
    DEF_v__h4535(2863311530u),
    DEF_v__h4148(2863311530u),
    DEF_v__h3759(2863311530u)
{
  symbol_count = 99u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTbCFFunctional::init_symbols_0()
{
  init_symbol(&symbols[0u],
	      "CAN_FIRE_RL_fifo_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_fifo_canonicalize,
	      1u);
  init_symbol(&symbols[1u],
	      "CAN_FIRE_RL_fifo_deqReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize,
	      1u);
  init_symbol(&symbols[2u],
	      "CAN_FIRE_RL_fifo_enqReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize,
	      1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_RL_m_check_fifos_first",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_check_fifos_first,
	      1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_m_check_fifos_not_empty",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_check_fifos_not_empty,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_m_check_fifos_not_full",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_check_fifos_not_full,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_m_check_outputs",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_check_outputs,
	      1u);
  init_symbol(&symbols[7u], "CAN_FIRE_RL_m_cycle_inc", SYM_DEF, &DEF_CAN_FIRE_RL_m_cycle_inc, 1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_m_feed_inputs", SYM_DEF, &DEF_CAN_FIRE_RL_m_feed_inputs, 1u);
  init_symbol(&symbols[9u], "CAN_FIRE_RL_m_init", SYM_DEF, &DEF_CAN_FIRE_RL_m_init, 1u);
  init_symbol(&symbols[10u],
	      "CAN_FIRE_RL_m_randomA_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomA_every,
	      1u);
  init_symbol(&symbols[11u],
	      "CAN_FIRE_RL_m_randomA_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomA_every_1,
	      1u);
  init_symbol(&symbols[12u],
	      "CAN_FIRE_RL_m_randomB_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomB_every,
	      1u);
  init_symbol(&symbols[13u],
	      "CAN_FIRE_RL_m_randomB_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomB_every_1,
	      1u);
  init_symbol(&symbols[14u],
	      "CAN_FIRE_RL_m_randomC_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomC_every,
	      1u);
  init_symbol(&symbols[15u],
	      "CAN_FIRE_RL_m_randomC_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomC_every_1,
	      1u);
  init_symbol(&symbols[16u],
	      "CAN_FIRE_RL_m_randomData_every",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomData_every,
	      1u);
  init_symbol(&symbols[17u],
	      "CAN_FIRE_RL_m_randomData_every_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_m_randomData_every_1,
	      1u);
  init_symbol(&symbols[18u], "CAN_FIRE_RL_m_stop_tb", SYM_DEF, &DEF_CAN_FIRE_RL_m_stop_tb, 1u);
  init_symbol(&symbols[19u], "fifo_data_0", SYM_MODULE, &INST_fifo_data_0);
  init_symbol(&symbols[20u], "fifo_data_1", SYM_MODULE, &INST_fifo_data_1);
  init_symbol(&symbols[21u], "fifo_deqReq_ehrReg", SYM_MODULE, &INST_fifo_deqReq_ehrReg);
  init_symbol(&symbols[22u],
	      "fifo_deqReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_fifo_deqReq_ignored_wires_0);
  init_symbol(&symbols[23u],
	      "fifo_deqReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_fifo_deqReq_ignored_wires_1);
  init_symbol(&symbols[24u],
	      "fifo_deqReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_fifo_deqReq_virtual_reg_0);
  init_symbol(&symbols[25u],
	      "fifo_deqReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_fifo_deqReq_virtual_reg_1);
  init_symbol(&symbols[26u], "fifo_deqReq_wires_0", SYM_MODULE, &INST_fifo_deqReq_wires_0);
  init_symbol(&symbols[27u], "fifo_deqReq_wires_1", SYM_MODULE, &INST_fifo_deqReq_wires_1);
  init_symbol(&symbols[28u], "fifo_empty", SYM_MODULE, &INST_fifo_empty);
  init_symbol(&symbols[29u], "fifo_empty__h3110", SYM_DEF, &DEF_fifo_empty__h3110, 1u);
  init_symbol(&symbols[30u], "fifo_enqReq_ehrReg", SYM_MODULE, &INST_fifo_enqReq_ehrReg);
  init_symbol(&symbols[31u],
	      "fifo_enqReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_fifo_enqReq_ignored_wires_0);
  init_symbol(&symbols[32u],
	      "fifo_enqReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_fifo_enqReq_ignored_wires_1);
  init_symbol(&symbols[33u],
	      "fifo_enqReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_fifo_enqReq_virtual_reg_0);
  init_symbol(&symbols[34u],
	      "fifo_enqReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_fifo_enqReq_virtual_reg_1);
  init_symbol(&symbols[35u], "fifo_enqReq_wires_0", SYM_MODULE, &INST_fifo_enqReq_wires_0);
  init_symbol(&symbols[36u], "fifo_enqReq_wires_1", SYM_MODULE, &INST_fifo_enqReq_wires_1);
  init_symbol(&symbols[37u], "fifo_full", SYM_MODULE, &INST_fifo_full);
  init_symbol(&symbols[38u], "fifo_full__h3124", SYM_DEF, &DEF_fifo_full__h3124, 1u);
  init_symbol(&symbols[39u], "m_cycle", SYM_MODULE, &INST_m_cycle);
  init_symbol(&symbols[40u], "m_input_count", SYM_MODULE, &INST_m_input_count);
  init_symbol(&symbols[41u], "m_output_count", SYM_MODULE, &INST_m_output_count);
  init_symbol(&symbols[42u], "m_randomA_ignore", SYM_MODULE, &INST_m_randomA_ignore);
  init_symbol(&symbols[43u], "m_randomA_initialized", SYM_MODULE, &INST_m_randomA_initialized);
  init_symbol(&symbols[44u], "m_randomA_zaz", SYM_MODULE, &INST_m_randomA_zaz);
  init_symbol(&symbols[45u], "m_randomB_ignore", SYM_MODULE, &INST_m_randomB_ignore);
  init_symbol(&symbols[46u], "m_randomB_initialized", SYM_MODULE, &INST_m_randomB_initialized);
  init_symbol(&symbols[47u], "m_randomB_zaz", SYM_MODULE, &INST_m_randomB_zaz);
  init_symbol(&symbols[48u], "m_randomC_ignore", SYM_MODULE, &INST_m_randomC_ignore);
  init_symbol(&symbols[49u], "m_randomC_initialized", SYM_MODULE, &INST_m_randomC_initialized);
  init_symbol(&symbols[50u], "m_randomC_zaz", SYM_MODULE, &INST_m_randomC_zaz);
  init_symbol(&symbols[51u], "m_randomData_ignore", SYM_MODULE, &INST_m_randomData_ignore);
  init_symbol(&symbols[52u], "m_randomData_initialized", SYM_MODULE, &INST_m_randomData_initialized);
  init_symbol(&symbols[53u], "m_randomData_zaz", SYM_MODULE, &INST_m_randomData_zaz);
  init_symbol(&symbols[54u], "m_ref_fifo", SYM_MODULE, &INST_m_ref_fifo);
  init_symbol(&symbols[55u], "RL_fifo_canonicalize", SYM_RULE);
  init_symbol(&symbols[56u], "RL_fifo_deqReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[57u], "RL_fifo_enqReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[58u], "RL_m_check_fifos_first", SYM_RULE);
  init_symbol(&symbols[59u], "RL_m_check_fifos_not_empty", SYM_RULE);
  init_symbol(&symbols[60u], "RL_m_check_fifos_not_full", SYM_RULE);
  init_symbol(&symbols[61u], "RL_m_check_outputs", SYM_RULE);
  init_symbol(&symbols[62u], "RL_m_cycle_inc", SYM_RULE);
  init_symbol(&symbols[63u], "RL_m_feed_inputs", SYM_RULE);
  init_symbol(&symbols[64u], "RL_m_init", SYM_RULE);
  init_symbol(&symbols[65u], "RL_m_randomA_every", SYM_RULE);
  init_symbol(&symbols[66u], "RL_m_randomA_every_1", SYM_RULE);
  init_symbol(&symbols[67u], "RL_m_randomB_every", SYM_RULE);
  init_symbol(&symbols[68u], "RL_m_randomB_every_1", SYM_RULE);
  init_symbol(&symbols[69u], "RL_m_randomC_every", SYM_RULE);
  init_symbol(&symbols[70u], "RL_m_randomC_every_1", SYM_RULE);
  init_symbol(&symbols[71u], "RL_m_randomData_every", SYM_RULE);
  init_symbol(&symbols[72u], "RL_m_randomData_every_1", SYM_RULE);
  init_symbol(&symbols[73u], "RL_m_stop_tb", SYM_RULE);
  init_symbol(&symbols[74u], "v__h3839", SYM_DEF, &DEF_v__h3839, 2u);
  init_symbol(&symbols[75u], "v__h4228", SYM_DEF, &DEF_v__h4228, 2u);
  init_symbol(&symbols[76u],
	      "WILL_FIRE_RL_fifo_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_fifo_canonicalize,
	      1u);
  init_symbol(&symbols[77u],
	      "WILL_FIRE_RL_fifo_deqReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize,
	      1u);
  init_symbol(&symbols[78u],
	      "WILL_FIRE_RL_fifo_enqReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize,
	      1u);
  init_symbol(&symbols[79u],
	      "WILL_FIRE_RL_m_check_fifos_first",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_check_fifos_first,
	      1u);
  init_symbol(&symbols[80u],
	      "WILL_FIRE_RL_m_check_fifos_not_empty",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_check_fifos_not_empty,
	      1u);
  init_symbol(&symbols[81u],
	      "WILL_FIRE_RL_m_check_fifos_not_full",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_check_fifos_not_full,
	      1u);
  init_symbol(&symbols[82u],
	      "WILL_FIRE_RL_m_check_outputs",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_check_outputs,
	      1u);
  init_symbol(&symbols[83u], "WILL_FIRE_RL_m_cycle_inc", SYM_DEF, &DEF_WILL_FIRE_RL_m_cycle_inc, 1u);
  init_symbol(&symbols[84u],
	      "WILL_FIRE_RL_m_feed_inputs",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_feed_inputs,
	      1u);
  init_symbol(&symbols[85u], "WILL_FIRE_RL_m_init", SYM_DEF, &DEF_WILL_FIRE_RL_m_init, 1u);
  init_symbol(&symbols[86u],
	      "WILL_FIRE_RL_m_randomA_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomA_every,
	      1u);
  init_symbol(&symbols[87u],
	      "WILL_FIRE_RL_m_randomA_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomA_every_1,
	      1u);
  init_symbol(&symbols[88u],
	      "WILL_FIRE_RL_m_randomB_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomB_every,
	      1u);
  init_symbol(&symbols[89u],
	      "WILL_FIRE_RL_m_randomB_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomB_every_1,
	      1u);
  init_symbol(&symbols[90u],
	      "WILL_FIRE_RL_m_randomC_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomC_every,
	      1u);
  init_symbol(&symbols[91u],
	      "WILL_FIRE_RL_m_randomC_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomC_every_1,
	      1u);
  init_symbol(&symbols[92u],
	      "WILL_FIRE_RL_m_randomData_every",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomData_every,
	      1u);
  init_symbol(&symbols[93u],
	      "WILL_FIRE_RL_m_randomData_every_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_m_randomData_every_1,
	      1u);
  init_symbol(&symbols[94u], "WILL_FIRE_RL_m_stop_tb", SYM_DEF, &DEF_WILL_FIRE_RL_m_stop_tb, 1u);
  init_symbol(&symbols[95u], "x__h6070", SYM_DEF, &DEF_x__h6070, 32u);
  init_symbol(&symbols[96u], "x__h6218", SYM_DEF, &DEF_x__h6218, 32u);
  init_symbol(&symbols[97u], "x_wget__h3702", SYM_DEF, &DEF_x_wget__h3702, 2u);
  init_symbol(&symbols[98u], "x_wget__h4091", SYM_DEF, &DEF_x_wget__h4091, 2u);
}


/* Rule actions */

void MOD_mkTbCFFunctional::RL_fifo_enqReq_canonicalize()
{
  tUInt32 DEF_IF_fifo_enqReq_wires_1_whas_THEN_fifo_enqReq_w_ETC___d22;
  tUInt8 DEF_x__h1153;
  tUInt8 DEF_fifo_enqReq_wires_1_whas____d1;
  tUInt32 DEF_fifo_enqReq_wires_1_wget____d2;
  DEF_fifo_enqReq_wires_1_wget____d2 = INST_fifo_enqReq_wires_1.METH_wget();
  DEF_fifo_enqReq_wires_0_wget____d5 = INST_fifo_enqReq_wires_0.METH_wget();
  DEF_fifo_enqReq_ehrReg___d7 = INST_fifo_enqReq_ehrReg.METH_read();
  DEF_fifo_enqReq_wires_1_whas____d1 = INST_fifo_enqReq_wires_1.METH_whas();
  DEF_fifo_enqReq_wires_0_whas____d4 = INST_fifo_enqReq_wires_0.METH_whas();
  DEF_x__h1151 = (tUInt8)((tUInt8)255u & DEF_fifo_enqReq_ehrReg___d7);
  DEF_x__h1153 = (tUInt8)((tUInt8)255u & DEF_fifo_enqReq_wires_1_wget____d2);
  DEF_x__h1152 = (tUInt8)((tUInt8)255u & DEF_fifo_enqReq_wires_0_wget____d5);
  DEF_fifo_enqReq_ehrReg_BIT_8___d8 = (tUInt8)(DEF_fifo_enqReq_ehrReg___d7 >> 8u);
  DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 = (tUInt8)(DEF_fifo_enqReq_wires_0_wget____d5 >> 8u);
  DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9 = DEF_fifo_enqReq_wires_0_whas____d4 ? DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 : DEF_fifo_enqReq_ehrReg_BIT_8___d8;
  DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19 = DEF_fifo_enqReq_wires_0_whas____d4 ? DEF_x__h1152 : DEF_x__h1151;
  DEF_IF_fifo_enqReq_wires_1_whas_THEN_fifo_enqReq_w_ETC___d22 = 511u & ((((tUInt32)(DEF_fifo_enqReq_wires_1_whas____d1 ? (tUInt8)(DEF_fifo_enqReq_wires_1_wget____d2 >> 8u) : DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9)) << 8u) | (tUInt32)(DEF_fifo_enqReq_wires_1_whas____d1 ? DEF_x__h1153 : DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19));
  INST_fifo_enqReq_ehrReg.METH_write(DEF_IF_fifo_enqReq_wires_1_whas_THEN_fifo_enqReq_w_ETC___d22);
}

void MOD_mkTbCFFunctional::RL_fifo_deqReq_canonicalize()
{
  tUInt8 DEF_IF_fifo_deqReq_wires_1_whas__3_THEN_fifo_deqRe_ETC___d29;
  DEF_fifo_deqReq_wires_0_whas____d25 = INST_fifo_deqReq_wires_0.METH_whas();
  DEF_fifo_deqReq_wires_0_wget____d26 = INST_fifo_deqReq_wires_0.METH_wget();
  DEF_fifo_deqReq_ehrReg__h1971 = INST_fifo_deqReq_ehrReg.METH_read();
  DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28 = DEF_fifo_deqReq_wires_0_whas____d25 ? DEF_fifo_deqReq_wires_0_wget____d26 : DEF_fifo_deqReq_ehrReg__h1971;
  DEF_IF_fifo_deqReq_wires_1_whas__3_THEN_fifo_deqRe_ETC___d29 = INST_fifo_deqReq_wires_1.METH_whas() ? INST_fifo_deqReq_wires_1.METH_wget() : DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28;
  INST_fifo_deqReq_ehrReg.METH_write(DEF_IF_fifo_deqReq_wires_1_whas__3_THEN_fifo_deqRe_ETC___d29);
}

void MOD_mkTbCFFunctional::RL_fifo_canonicalize()
{
  tUInt8 DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d35;
  tUInt8 DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d44;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d48;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d66;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d61;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d62;
  tUInt32 DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d32;
  tUInt32 DEF__0_CONCAT_DONTCARE___d30;
  tUInt8 DEF_IF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_ETC___d56;
  tUInt8 DEF_x__h3215;
  tUInt8 DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d52;
  tUInt8 DEF_fifo_deqReq_virtual_reg_1_read____d36;
  tUInt8 DEF_NOT_fifo_deqReq_virtual_reg_1_read__6_7_AND_IF_ETC___d38;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read____d33;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d47;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d50;
  tUInt8 DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d64;
  tUInt8 DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d57;
  tUInt8 DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d46;
  tUInt8 DEF_fifo_deqReq_virtual_reg_1_read__6_OR_IF_fifo_d_ETC___d43;
  DEF_fifo_empty__h3110 = INST_fifo_empty.METH_read();
  DEF_fifo_full__h3124 = INST_fifo_full.METH_read();
  DEF_fifo_enqReq_virtual_reg_1_read____d33 = INST_fifo_enqReq_virtual_reg_1.METH_read();
  DEF_fifo_deqReq_virtual_reg_1_read____d36 = INST_fifo_deqReq_virtual_reg_1.METH_read();
  DEF_fifo_enqReq_wires_0_wget____d5 = INST_fifo_enqReq_wires_0.METH_wget();
  DEF_fifo_enqReq_ehrReg___d7 = INST_fifo_enqReq_ehrReg.METH_read();
  DEF_fifo_deqReq_wires_0_whas____d25 = INST_fifo_deqReq_wires_0.METH_whas();
  DEF_x__h3215 = INST_fifo_data_0.METH_read();
  DEF_fifo_deqReq_wires_0_wget____d26 = INST_fifo_deqReq_wires_0.METH_wget();
  DEF_fifo_deqReq_ehrReg__h1971 = INST_fifo_deqReq_ehrReg.METH_read();
  DEF_fifo_deqReq_virtual_reg_1_read__6_OR_IF_fifo_d_ETC___d43 = DEF_fifo_deqReq_virtual_reg_1_read____d36 || (DEF_fifo_deqReq_wires_0_whas____d25 ? !DEF_fifo_deqReq_wires_0_wget____d26 : !DEF_fifo_deqReq_ehrReg__h1971);
  DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28 = DEF_fifo_deqReq_wires_0_whas____d25 ? DEF_fifo_deqReq_wires_0_wget____d26 : DEF_fifo_deqReq_ehrReg__h1971;
  DEF_NOT_fifo_deqReq_virtual_reg_1_read__6_7_AND_IF_ETC___d38 = !DEF_fifo_deqReq_virtual_reg_1_read____d36 && DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28;
  DEF_fifo_enqReq_wires_0_whas____d4 = INST_fifo_enqReq_wires_0.METH_whas();
  DEF_x__h1152 = (tUInt8)((tUInt8)255u & DEF_fifo_enqReq_wires_0_wget____d5);
  DEF_x__h1151 = (tUInt8)((tUInt8)255u & DEF_fifo_enqReq_ehrReg___d7);
  DEF_fifo_enqReq_ehrReg_BIT_8___d8 = (tUInt8)(DEF_fifo_enqReq_ehrReg___d7 >> 8u);
  DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 = (tUInt8)(DEF_fifo_enqReq_wires_0_wget____d5 >> 8u);
  DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9 = DEF_fifo_enqReq_wires_0_whas____d4 ? DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 : DEF_fifo_enqReq_ehrReg_BIT_8___d8;
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d47 = DEF_fifo_enqReq_virtual_reg_1_read____d33 || (DEF_fifo_enqReq_wires_0_whas____d4 ? !DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 : !DEF_fifo_enqReq_ehrReg_BIT_8___d8);
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d57 = DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d47 || DEF_fifo_deqReq_virtual_reg_1_read__6_OR_IF_fifo_d_ETC___d43;
  DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19 = DEF_fifo_enqReq_wires_0_whas____d4 ? DEF_x__h1152 : DEF_x__h1151;
  DEF_NOT_fifo_empty_5___d63 = !DEF_fifo_empty__h3110;
  DEF__0_CONCAT_DONTCARE___d30 = 170u;
  DEF_NOT_fifo_full_9___d58 = !DEF_fifo_full__h3124;
  DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d32 = 511u & ((((tUInt32)(DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9)) << 8u) | (tUInt32)(DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19));
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d62 = DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d47 || DEF_NOT_fifo_deqReq_virtual_reg_1_read__6_7_AND_IF_ETC___d38;
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d48 = DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d47 && DEF_NOT_fifo_deqReq_virtual_reg_1_read__6_7_AND_IF_ETC___d38;
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d50 = DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d48 && DEF_fifo_full__h3124;
  DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d35 = !DEF_fifo_enqReq_virtual_reg_1_read____d33 && DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9;
  DEF_IF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_ETC___d56 = DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d35 && (DEF_NOT_fifo_deqReq_virtual_reg_1_read__6_7_AND_IF_ETC___d38 || DEF_fifo_deqReq_virtual_reg_1_read__6_OR_IF_fifo_d_ETC___d43) ? DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19 : DEF_x__h3215;
  DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d44 = DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d35 && DEF_fifo_deqReq_virtual_reg_1_read__6_OR_IF_fifo_d_ETC___d43;
  DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d46 = DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d44 && DEF_fifo_empty__h3110;
  DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d64 = DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d44 && DEF_NOT_fifo_empty_5___d63;
  DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d52 = (DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d35 && DEF_NOT_fifo_deqReq_virtual_reg_1_read__6_7_AND_IF_ETC___d38) || (DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d46 || DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d50);
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d61 = DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d57 && (DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d46 || (DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d48 && DEF_NOT_fifo_full_9___d58));
  DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d66 = DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d57 && (DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d64 || DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d50);
  INST_fifo_deqReq_wires_1.METH_wset((tUInt8)0u);
  INST_fifo_deqReq_ignored_wires_1.METH_wset(DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28);
  INST_fifo_deqReq_virtual_reg_1.METH_write((tUInt8)0u);
  INST_fifo_enqReq_ignored_wires_1.METH_wset(DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d32);
  INST_fifo_enqReq_wires_1.METH_wset(DEF__0_CONCAT_DONTCARE___d30);
  INST_fifo_enqReq_virtual_reg_1.METH_write((tUInt8)0u);
  if (DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d52)
    INST_fifo_data_1.METH_write(DEF_IF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_ETC___d56);
  if (DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d61)
    INST_fifo_empty.METH_write(DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d62);
  if (DEF_fifo_enqReq_virtual_reg_1_read__3_OR_IF_fifo_e_ETC___d66)
    INST_fifo_full.METH_write(DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d44);
  if (DEF_NOT_fifo_enqReq_virtual_reg_1_read__3_4_AND_IF_ETC___d64)
    INST_fifo_data_0.METH_write(DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19);
}

void MOD_mkTbCFFunctional::RL_m_randomA_every()
{
  tUInt8 DEF_new_value__h3801;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h3759 = rand32();
  DEF_new_value__h3801 = (tUInt8)((tUInt8)3u & DEF_v__h3759);
  INST_m_randomA_zaz.METH_wset(DEF_new_value__h3801);
}

void MOD_mkTbCFFunctional::RL_m_randomA_every_1()
{
  DEF_x_wget__h3702 = INST_m_randomA_zaz.METH_wget();
  DEF_v__h3839 = INST_m_randomA_zaz.METH_whas() ? DEF_x_wget__h3702 : (tUInt8)0u;
  INST_m_randomA_ignore.METH_wset(DEF_v__h3839);
}

void MOD_mkTbCFFunctional::RL_m_randomB_every()
{
  tUInt8 DEF_new_value__h4190;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h4148 = rand32();
  DEF_new_value__h4190 = (tUInt8)((tUInt8)3u & DEF_v__h4148);
  INST_m_randomB_zaz.METH_wset(DEF_new_value__h4190);
}

void MOD_mkTbCFFunctional::RL_m_randomB_every_1()
{
  DEF_x_wget__h4091 = INST_m_randomB_zaz.METH_wget();
  DEF_v__h4228 = INST_m_randomB_zaz.METH_whas() ? DEF_x_wget__h4091 : (tUInt8)0u;
  INST_m_randomB_ignore.METH_wset(DEF_v__h4228);
}

void MOD_mkTbCFFunctional::RL_m_randomC_every()
{
  tUInt8 DEF_new_value__h4577;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h4535 = rand32();
  DEF_new_value__h4577 = (tUInt8)((tUInt8)15u & DEF_v__h4535);
  INST_m_randomC_zaz.METH_wset(DEF_new_value__h4577);
}

void MOD_mkTbCFFunctional::RL_m_randomC_every_1()
{
  tUInt8 DEF_v__h4615;
  tUInt8 DEF_x_wget__h4478;
  DEF_x_wget__h4478 = INST_m_randomC_zaz.METH_wget();
  DEF_v__h4615 = INST_m_randomC_zaz.METH_whas() ? DEF_x_wget__h4478 : (tUInt8)0u;
  INST_m_randomC_ignore.METH_wset(DEF_v__h4615);
}

void MOD_mkTbCFFunctional::RL_m_randomData_every()
{
  tUInt8 DEF_new_value__h4967;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h4925 = rand32();
  DEF_new_value__h4967 = (tUInt8)((tUInt8)255u & DEF_v__h4925);
  INST_m_randomData_zaz.METH_wset(DEF_new_value__h4967);
}

void MOD_mkTbCFFunctional::RL_m_randomData_every_1()
{
  DEF_x_wget__h4868 = INST_m_randomData_zaz.METH_wget();
  DEF_v__h5005 = INST_m_randomData_zaz.METH_whas() ? DEF_x_wget__h4868 : (tUInt8)0u;
  INST_m_randomData_ignore.METH_wset(DEF_v__h5005);
}

void MOD_mkTbCFFunctional::RL_m_init()
{
  INST_m_randomA_initialized.METH_write((tUInt8)1u);
  INST_m_randomB_initialized.METH_write((tUInt8)1u);
  INST_m_randomC_initialized.METH_write((tUInt8)1u);
  INST_m_randomData_initialized.METH_write((tUInt8)1u);
}

void MOD_mkTbCFFunctional::RL_m_feed_inputs()
{
  tUInt32 DEF_x__h5461;
  tUInt8 DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106;
  tUInt32 DEF_fifo_enqReq_ehrReg_BIT_8_CONCAT_IF_fifo_enqReq_ETC___d109;
  tUInt32 DEF__1_CONCAT_IF_m_randomData_zaz_whas__2_THEN_m_ra_ETC___d107;
  DEF_x__h6070 = INST_m_input_count.METH_read();
  DEF_fifo_enqReq_ehrReg___d7 = INST_fifo_enqReq_ehrReg.METH_read();
  DEF_x_wget__h4868 = INST_m_randomData_zaz.METH_wget();
  DEF_x_wget__h3702 = INST_m_randomA_zaz.METH_wget();
  DEF_x__h1151 = (tUInt8)((tUInt8)255u & DEF_fifo_enqReq_ehrReg___d7);
  DEF_fifo_enqReq_ehrReg_BIT_8___d8 = (tUInt8)(DEF_fifo_enqReq_ehrReg___d7 >> 8u);
  DEF_v__h5005 = INST_m_randomData_zaz.METH_whas() ? DEF_x_wget__h4868 : (tUInt8)0u;
  DEF_v__h3839 = INST_m_randomA_zaz.METH_whas() ? DEF_x_wget__h3702 : (tUInt8)0u;
  DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97 = DEF_v__h3839 == (tUInt8)0u;
  DEF__1_CONCAT_IF_m_randomData_zaz_whas__2_THEN_m_ra_ETC___d107 = 511u & ((((tUInt32)((tUInt8)1u)) << 8u) | (tUInt32)(DEF_v__h5005));
  DEF_fifo_enqReq_ehrReg_BIT_8_CONCAT_IF_fifo_enqReq_ETC___d109 = 511u & ((((tUInt32)(DEF_fifo_enqReq_ehrReg_BIT_8___d8)) << 8u) | (tUInt32)(DEF_x__h1151));
  DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106 = !DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97;
  DEF_x__h5461 = DEF_x__h6070 + 1u;
  if (DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106)
    INST_fifo_enqReq_wires_0.METH_wset(DEF__1_CONCAT_IF_m_randomData_zaz_whas__2_THEN_m_ra_ETC___d107);
  if (DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106)
    INST_fifo_enqReq_ignored_wires_0.METH_wset(DEF_fifo_enqReq_ehrReg_BIT_8_CONCAT_IF_fifo_enqReq_ETC___d109);
  if (DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106)
    INST_fifo_enqReq_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106)
    INST_m_ref_fifo.METH_enq(DEF_v__h5005);
  if (DEF_NOT_IF_m_randomA_zaz_whas__1_THEN_m_randomA_za_ETC___d106)
    INST_m_input_count.METH_write(DEF_x__h5461);
}

void MOD_mkTbCFFunctional::RL_m_check_outputs()
{
  tUInt32 DEF_x__h5816;
  tUInt8 DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116;
  tUInt8 DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d121;
  DEF_x__h5820 = INST_m_output_count.METH_read();
  DEF_y__h6005 = INST_fifo_data_1.METH_read();
  DEF_x__h6004 = INST_m_ref_fifo.METH_first();
  DEF_x_wget__h4091 = INST_m_randomB_zaz.METH_wget();
  DEF_fifo_deqReq_ehrReg__h1971 = INST_fifo_deqReq_ehrReg.METH_read();
  DEF_v__h4228 = INST_m_randomB_zaz.METH_whas() ? DEF_x_wget__h4091 : (tUInt8)0u;
  DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111 = DEF_v__h4228 == (tUInt8)0u;
  DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116 = !DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111;
  DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d121 = DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116 && !(DEF_y__h6005 == DEF_x__h6004);
  DEF_x__h5816 = DEF_x__h5820 + 1u;
  if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116)
    INST_fifo_deqReq_wires_0.METH_wset((tUInt8)1u);
  if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116)
    INST_fifo_deqReq_ignored_wires_0.METH_wset(DEF_fifo_deqReq_ehrReg__h1971);
  if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116)
    INST_fifo_deqReq_virtual_reg_0.METH_write((tUInt8)0u);
  if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116)
    INST_m_ref_fifo.METH_deq();
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d121)
      dollar_display(sim_hdl, this, "s,8", &__str_literal_1, DEF_x__h6004);
    if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d121)
      dollar_finish(sim_hdl, "32", 1u);
  }
  if (DEF_NOT_IF_m_randomB_zaz_whas__8_THEN_m_randomB_za_ETC___d116)
    INST_m_output_count.METH_write(DEF_x__h5816);
}

void MOD_mkTbCFFunctional::RL_m_check_fifos_not_full()
{
  tUInt8 DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d127;
  tUInt8 DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d126;
  tUInt8 DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d128;
  DEF_fifo_full__h3124 = INST_fifo_full.METH_read();
  DEF_NOT_fifo_full_9___d58 = !DEF_fifo_full__h3124;
  DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d126 = !(INST_m_ref_fifo.METH_notFull() == DEF_NOT_fifo_full_9___d58);
  DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d128 = DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d126 && DEF_NOT_fifo_full_9___d58;
  DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d127 = DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d126 && DEF_fifo_full__h3124;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d127)
      dollar_display(sim_hdl, this, "s", &__str_literal_2);
    if (DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d127)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d128)
      dollar_display(sim_hdl, this, "s", &__str_literal_3);
    if (DEF_NOT_m_ref_fifo_notFull__24_EQ_NOT_fifo_full_9__ETC___d128)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbCFFunctional::RL_m_check_fifos_not_empty()
{
  tUInt8 DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d132;
  tUInt8 DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d131;
  tUInt8 DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d133;
  DEF_fifo_empty__h3110 = INST_fifo_empty.METH_read();
  DEF_NOT_fifo_empty_5___d63 = !DEF_fifo_empty__h3110;
  DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d131 = !(INST_m_ref_fifo.METH_notEmpty() == DEF_NOT_fifo_empty_5___d63);
  DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d133 = DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d131 && DEF_NOT_fifo_empty_5___d63;
  DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d132 = DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d131 && DEF_fifo_empty__h3110;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d132)
      dollar_display(sim_hdl, this, "s", &__str_literal_4);
    if (DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d132)
      dollar_finish(sim_hdl, "32", 1u);
    if (DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d133)
      dollar_display(sim_hdl, this, "s", &__str_literal_5);
    if (DEF_NOT_m_ref_fifo_notEmpty__29_EQ_NOT_fifo_empty__ETC___d133)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbCFFunctional::RL_m_check_fifos_first()
{
  tUInt8 DEF_NOT_m_ref_fifo_first__18_EQ_fifo_data_1_17_34___d135;
  DEF_y__h6005 = INST_fifo_data_1.METH_read();
  DEF_x__h6004 = INST_m_ref_fifo.METH_first();
  DEF_NOT_m_ref_fifo_first__18_EQ_fifo_data_1_17_34___d135 = !(DEF_x__h6004 == DEF_y__h6005);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_m_ref_fifo_first__18_EQ_fifo_data_1_17_34___d135)
      dollar_display(sim_hdl, this, "s,8,8", &__str_literal_6, DEF_y__h6005, DEF_x__h6004);
    if (DEF_NOT_m_ref_fifo_first__18_EQ_fifo_data_1_17_34___d135)
      dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbCFFunctional::RL_m_stop_tb()
{
  tUInt8 DEF_NOT_m_input_count_03_EQ_1024_36___d139;
  DEF_x__h5820 = INST_m_output_count.METH_read();
  DEF_x__h6070 = INST_m_input_count.METH_read();
  DEF_m_input_count_03_EQ_1024___d136 = DEF_x__h6070 == 1024u;
  DEF_NOT_m_input_count_03_EQ_1024_36___d139 = !DEF_m_input_count_03_EQ_1024___d136;
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_m_input_count_03_EQ_1024___d136)
      dollar_display(sim_hdl, this, "s", &__str_literal_7);
    if (DEF_m_input_count_03_EQ_1024___d136)
      dollar_display(sim_hdl, this, "s,32", &__str_literal_8, DEF_x__h5820);
    if (DEF_NOT_m_input_count_03_EQ_1024_36___d139)
      dollar_display(sim_hdl, this, "s", &__str_literal_9);
    dollar_finish(sim_hdl, "32", 1u);
  }
}

void MOD_mkTbCFFunctional::RL_m_cycle_inc()
{
  tUInt32 DEF_x__h6213;
  DEF_x__h6218 = INST_m_cycle.METH_read();
  DEF_x__h6213 = DEF_x__h6218 + 1u;
  INST_m_cycle.METH_write(DEF_x__h6213);
}


/* Methods */


/* Reset routines */

void MOD_mkTbCFFunctional::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_m_ref_fifo.reset_RST(ARG_rst_in);
  INST_m_randomData_initialized.reset_RST(ARG_rst_in);
  INST_m_randomC_initialized.reset_RST(ARG_rst_in);
  INST_m_randomB_initialized.reset_RST(ARG_rst_in);
  INST_m_randomA_initialized.reset_RST(ARG_rst_in);
  INST_m_output_count.reset_RST(ARG_rst_in);
  INST_m_input_count.reset_RST(ARG_rst_in);
  INST_m_cycle.reset_RST(ARG_rst_in);
  INST_fifo_full.reset_RST(ARG_rst_in);
  INST_fifo_enqReq_ehrReg.reset_RST(ARG_rst_in);
  INST_fifo_empty.reset_RST(ARG_rst_in);
  INST_fifo_deqReq_ehrReg.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTbCFFunctional::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTbCFFunctional::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_fifo_data_0.dump_state(indent + 2u);
  INST_fifo_data_1.dump_state(indent + 2u);
  INST_fifo_deqReq_ehrReg.dump_state(indent + 2u);
  INST_fifo_deqReq_ignored_wires_0.dump_state(indent + 2u);
  INST_fifo_deqReq_ignored_wires_1.dump_state(indent + 2u);
  INST_fifo_deqReq_virtual_reg_0.dump_state(indent + 2u);
  INST_fifo_deqReq_virtual_reg_1.dump_state(indent + 2u);
  INST_fifo_deqReq_wires_0.dump_state(indent + 2u);
  INST_fifo_deqReq_wires_1.dump_state(indent + 2u);
  INST_fifo_empty.dump_state(indent + 2u);
  INST_fifo_enqReq_ehrReg.dump_state(indent + 2u);
  INST_fifo_enqReq_ignored_wires_0.dump_state(indent + 2u);
  INST_fifo_enqReq_ignored_wires_1.dump_state(indent + 2u);
  INST_fifo_enqReq_virtual_reg_0.dump_state(indent + 2u);
  INST_fifo_enqReq_virtual_reg_1.dump_state(indent + 2u);
  INST_fifo_enqReq_wires_0.dump_state(indent + 2u);
  INST_fifo_enqReq_wires_1.dump_state(indent + 2u);
  INST_fifo_full.dump_state(indent + 2u);
  INST_m_cycle.dump_state(indent + 2u);
  INST_m_input_count.dump_state(indent + 2u);
  INST_m_output_count.dump_state(indent + 2u);
  INST_m_randomA_ignore.dump_state(indent + 2u);
  INST_m_randomA_initialized.dump_state(indent + 2u);
  INST_m_randomA_zaz.dump_state(indent + 2u);
  INST_m_randomB_ignore.dump_state(indent + 2u);
  INST_m_randomB_initialized.dump_state(indent + 2u);
  INST_m_randomB_zaz.dump_state(indent + 2u);
  INST_m_randomC_ignore.dump_state(indent + 2u);
  INST_m_randomC_initialized.dump_state(indent + 2u);
  INST_m_randomC_zaz.dump_state(indent + 2u);
  INST_m_randomData_ignore.dump_state(indent + 2u);
  INST_m_randomData_initialized.dump_state(indent + 2u);
  INST_m_randomData_zaz.dump_state(indent + 2u);
  INST_m_ref_fifo.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTbCFFunctional::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 108u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_fifo_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_fifo_deqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_fifo_enqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_check_fifos_first", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_check_fifos_not_empty", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_check_fifos_not_full", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_check_outputs", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_cycle_inc", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_feed_inputs", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_init", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomC_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomC_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomData_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_randomData_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_m_stop_tb", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_fifo_empty_5___d63", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_fifo_full_9___d58", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_fifo_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_fifo_deqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_fifo_enqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_check_fifos_first", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_check_fifos_not_empty", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_check_fifos_not_full", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_check_outputs", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_cycle_inc", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_feed_inputs", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_init", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomA_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomA_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomB_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomB_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomC_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomC_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomData_every", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_randomData_every_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_m_stop_tb", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_deqReq_ehrReg__h1971", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_deqReq_wires_0_wget____d26", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_deqReq_wires_0_whas____d25", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_empty__h3110", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_enqReq_ehrReg_BIT_8___d8", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_enqReq_ehrReg___d7", 9u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_enqReq_wires_0_wget_BIT_8___d6", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_enqReq_wires_0_wget____d5", 9u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_enqReq_wires_0_whas____d4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "fifo_full__h3124", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_input_count_03_EQ_1024___d136", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3759", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h3839", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4148", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4228", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4535", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4925", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h5005", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1151", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1152", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5820", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h6004", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h6070", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h6218", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h3702", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h4091", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h4868", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h6005", 8u);
  num = INST_fifo_data_0.dump_VCD_defs(num);
  num = INST_fifo_data_1.dump_VCD_defs(num);
  num = INST_fifo_deqReq_ehrReg.dump_VCD_defs(num);
  num = INST_fifo_deqReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_fifo_deqReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_fifo_deqReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_fifo_deqReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_fifo_deqReq_wires_0.dump_VCD_defs(num);
  num = INST_fifo_deqReq_wires_1.dump_VCD_defs(num);
  num = INST_fifo_empty.dump_VCD_defs(num);
  num = INST_fifo_enqReq_ehrReg.dump_VCD_defs(num);
  num = INST_fifo_enqReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_fifo_enqReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_fifo_enqReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_fifo_enqReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_fifo_enqReq_wires_0.dump_VCD_defs(num);
  num = INST_fifo_enqReq_wires_1.dump_VCD_defs(num);
  num = INST_fifo_full.dump_VCD_defs(num);
  num = INST_m_cycle.dump_VCD_defs(num);
  num = INST_m_input_count.dump_VCD_defs(num);
  num = INST_m_output_count.dump_VCD_defs(num);
  num = INST_m_randomA_ignore.dump_VCD_defs(num);
  num = INST_m_randomA_initialized.dump_VCD_defs(num);
  num = INST_m_randomA_zaz.dump_VCD_defs(num);
  num = INST_m_randomB_ignore.dump_VCD_defs(num);
  num = INST_m_randomB_initialized.dump_VCD_defs(num);
  num = INST_m_randomB_zaz.dump_VCD_defs(num);
  num = INST_m_randomC_ignore.dump_VCD_defs(num);
  num = INST_m_randomC_initialized.dump_VCD_defs(num);
  num = INST_m_randomC_zaz.dump_VCD_defs(num);
  num = INST_m_randomData_ignore.dump_VCD_defs(num);
  num = INST_m_randomData_initialized.dump_VCD_defs(num);
  num = INST_m_randomData_zaz.dump_VCD_defs(num);
  num = INST_m_ref_fifo.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTbCFFunctional::dump_VCD(tVCDDumpType dt,
				    unsigned int levels,
				    MOD_mkTbCFFunctional &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkTbCFFunctional::vcd_defs(tVCDDumpType dt, MOD_mkTbCFFunctional &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 9u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 9u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 8u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_fifo_canonicalize) != DEF_CAN_FIRE_RL_fifo_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_fifo_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_fifo_canonicalize = DEF_CAN_FIRE_RL_fifo_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize) != DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize = DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize) != DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize = DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_check_fifos_first) != DEF_CAN_FIRE_RL_m_check_fifos_first)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_check_fifos_first, 1u);
	backing.DEF_CAN_FIRE_RL_m_check_fifos_first = DEF_CAN_FIRE_RL_m_check_fifos_first;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_check_fifos_not_empty) != DEF_CAN_FIRE_RL_m_check_fifos_not_empty)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_check_fifos_not_empty, 1u);
	backing.DEF_CAN_FIRE_RL_m_check_fifos_not_empty = DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_check_fifos_not_full) != DEF_CAN_FIRE_RL_m_check_fifos_not_full)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_check_fifos_not_full, 1u);
	backing.DEF_CAN_FIRE_RL_m_check_fifos_not_full = DEF_CAN_FIRE_RL_m_check_fifos_not_full;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_check_outputs) != DEF_CAN_FIRE_RL_m_check_outputs)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_check_outputs, 1u);
	backing.DEF_CAN_FIRE_RL_m_check_outputs = DEF_CAN_FIRE_RL_m_check_outputs;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_cycle_inc) != DEF_CAN_FIRE_RL_m_cycle_inc)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_cycle_inc, 1u);
	backing.DEF_CAN_FIRE_RL_m_cycle_inc = DEF_CAN_FIRE_RL_m_cycle_inc;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_feed_inputs) != DEF_CAN_FIRE_RL_m_feed_inputs)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_feed_inputs, 1u);
	backing.DEF_CAN_FIRE_RL_m_feed_inputs = DEF_CAN_FIRE_RL_m_feed_inputs;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_init) != DEF_CAN_FIRE_RL_m_init)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_init, 1u);
	backing.DEF_CAN_FIRE_RL_m_init = DEF_CAN_FIRE_RL_m_init;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomA_every) != DEF_CAN_FIRE_RL_m_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomA_every, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomA_every = DEF_CAN_FIRE_RL_m_randomA_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomA_every_1) != DEF_CAN_FIRE_RL_m_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomA_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomA_every_1 = DEF_CAN_FIRE_RL_m_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomB_every) != DEF_CAN_FIRE_RL_m_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomB_every, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomB_every = DEF_CAN_FIRE_RL_m_randomB_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomB_every_1) != DEF_CAN_FIRE_RL_m_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomB_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomB_every_1 = DEF_CAN_FIRE_RL_m_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomC_every) != DEF_CAN_FIRE_RL_m_randomC_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomC_every, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomC_every = DEF_CAN_FIRE_RL_m_randomC_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomC_every_1) != DEF_CAN_FIRE_RL_m_randomC_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomC_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomC_every_1 = DEF_CAN_FIRE_RL_m_randomC_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomData_every) != DEF_CAN_FIRE_RL_m_randomData_every)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomData_every, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomData_every = DEF_CAN_FIRE_RL_m_randomData_every;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_randomData_every_1) != DEF_CAN_FIRE_RL_m_randomData_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_randomData_every_1, 1u);
	backing.DEF_CAN_FIRE_RL_m_randomData_every_1 = DEF_CAN_FIRE_RL_m_randomData_every_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_m_stop_tb) != DEF_CAN_FIRE_RL_m_stop_tb)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_m_stop_tb, 1u);
	backing.DEF_CAN_FIRE_RL_m_stop_tb = DEF_CAN_FIRE_RL_m_stop_tb;
      }
      ++num;
      if ((backing.DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28) != DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28, 1u);
	backing.DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28 = DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28;
      }
      ++num;
      if ((backing.DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19) != DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19, 8u);
	backing.DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19 = DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19;
      }
      ++num;
      if ((backing.DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9) != DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9, 1u);
	backing.DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9 = DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9;
      }
      ++num;
      if ((backing.DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97) != DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97, 1u);
	backing.DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97 = DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97;
      }
      ++num;
      if ((backing.DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111) != DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111, 1u);
	backing.DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111 = DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111;
      }
      ++num;
      if ((backing.DEF_NOT_fifo_empty_5___d63) != DEF_NOT_fifo_empty_5___d63)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_fifo_empty_5___d63, 1u);
	backing.DEF_NOT_fifo_empty_5___d63 = DEF_NOT_fifo_empty_5___d63;
      }
      ++num;
      if ((backing.DEF_NOT_fifo_full_9___d58) != DEF_NOT_fifo_full_9___d58)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_fifo_full_9___d58, 1u);
	backing.DEF_NOT_fifo_full_9___d58 = DEF_NOT_fifo_full_9___d58;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_fifo_canonicalize) != DEF_WILL_FIRE_RL_fifo_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_fifo_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_fifo_canonicalize = DEF_WILL_FIRE_RL_fifo_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize) != DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize = DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize) != DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize = DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_check_fifos_first) != DEF_WILL_FIRE_RL_m_check_fifos_first)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_check_fifos_first, 1u);
	backing.DEF_WILL_FIRE_RL_m_check_fifos_first = DEF_WILL_FIRE_RL_m_check_fifos_first;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_check_fifos_not_empty) != DEF_WILL_FIRE_RL_m_check_fifos_not_empty)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_check_fifos_not_empty, 1u);
	backing.DEF_WILL_FIRE_RL_m_check_fifos_not_empty = DEF_WILL_FIRE_RL_m_check_fifos_not_empty;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_check_fifos_not_full) != DEF_WILL_FIRE_RL_m_check_fifos_not_full)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_check_fifos_not_full, 1u);
	backing.DEF_WILL_FIRE_RL_m_check_fifos_not_full = DEF_WILL_FIRE_RL_m_check_fifos_not_full;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_check_outputs) != DEF_WILL_FIRE_RL_m_check_outputs)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_check_outputs, 1u);
	backing.DEF_WILL_FIRE_RL_m_check_outputs = DEF_WILL_FIRE_RL_m_check_outputs;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_cycle_inc) != DEF_WILL_FIRE_RL_m_cycle_inc)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_cycle_inc, 1u);
	backing.DEF_WILL_FIRE_RL_m_cycle_inc = DEF_WILL_FIRE_RL_m_cycle_inc;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_feed_inputs) != DEF_WILL_FIRE_RL_m_feed_inputs)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_feed_inputs, 1u);
	backing.DEF_WILL_FIRE_RL_m_feed_inputs = DEF_WILL_FIRE_RL_m_feed_inputs;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_init) != DEF_WILL_FIRE_RL_m_init)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_init, 1u);
	backing.DEF_WILL_FIRE_RL_m_init = DEF_WILL_FIRE_RL_m_init;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomA_every) != DEF_WILL_FIRE_RL_m_randomA_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomA_every, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomA_every = DEF_WILL_FIRE_RL_m_randomA_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomA_every_1) != DEF_WILL_FIRE_RL_m_randomA_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomA_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomA_every_1 = DEF_WILL_FIRE_RL_m_randomA_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomB_every) != DEF_WILL_FIRE_RL_m_randomB_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomB_every, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomB_every = DEF_WILL_FIRE_RL_m_randomB_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomB_every_1) != DEF_WILL_FIRE_RL_m_randomB_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomB_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomB_every_1 = DEF_WILL_FIRE_RL_m_randomB_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomC_every) != DEF_WILL_FIRE_RL_m_randomC_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomC_every, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomC_every = DEF_WILL_FIRE_RL_m_randomC_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomC_every_1) != DEF_WILL_FIRE_RL_m_randomC_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomC_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomC_every_1 = DEF_WILL_FIRE_RL_m_randomC_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomData_every) != DEF_WILL_FIRE_RL_m_randomData_every)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomData_every, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomData_every = DEF_WILL_FIRE_RL_m_randomData_every;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_randomData_every_1) != DEF_WILL_FIRE_RL_m_randomData_every_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_randomData_every_1, 1u);
	backing.DEF_WILL_FIRE_RL_m_randomData_every_1 = DEF_WILL_FIRE_RL_m_randomData_every_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_m_stop_tb) != DEF_WILL_FIRE_RL_m_stop_tb)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_m_stop_tb, 1u);
	backing.DEF_WILL_FIRE_RL_m_stop_tb = DEF_WILL_FIRE_RL_m_stop_tb;
      }
      ++num;
      if ((backing.DEF_fifo_deqReq_ehrReg__h1971) != DEF_fifo_deqReq_ehrReg__h1971)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_deqReq_ehrReg__h1971, 1u);
	backing.DEF_fifo_deqReq_ehrReg__h1971 = DEF_fifo_deqReq_ehrReg__h1971;
      }
      ++num;
      if ((backing.DEF_fifo_deqReq_wires_0_wget____d26) != DEF_fifo_deqReq_wires_0_wget____d26)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_deqReq_wires_0_wget____d26, 1u);
	backing.DEF_fifo_deqReq_wires_0_wget____d26 = DEF_fifo_deqReq_wires_0_wget____d26;
      }
      ++num;
      if ((backing.DEF_fifo_deqReq_wires_0_whas____d25) != DEF_fifo_deqReq_wires_0_whas____d25)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_deqReq_wires_0_whas____d25, 1u);
	backing.DEF_fifo_deqReq_wires_0_whas____d25 = DEF_fifo_deqReq_wires_0_whas____d25;
      }
      ++num;
      if ((backing.DEF_fifo_empty__h3110) != DEF_fifo_empty__h3110)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_empty__h3110, 1u);
	backing.DEF_fifo_empty__h3110 = DEF_fifo_empty__h3110;
      }
      ++num;
      if ((backing.DEF_fifo_enqReq_ehrReg_BIT_8___d8) != DEF_fifo_enqReq_ehrReg_BIT_8___d8)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_enqReq_ehrReg_BIT_8___d8, 1u);
	backing.DEF_fifo_enqReq_ehrReg_BIT_8___d8 = DEF_fifo_enqReq_ehrReg_BIT_8___d8;
      }
      ++num;
      if ((backing.DEF_fifo_enqReq_ehrReg___d7) != DEF_fifo_enqReq_ehrReg___d7)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_enqReq_ehrReg___d7, 9u);
	backing.DEF_fifo_enqReq_ehrReg___d7 = DEF_fifo_enqReq_ehrReg___d7;
      }
      ++num;
      if ((backing.DEF_fifo_enqReq_wires_0_wget_BIT_8___d6) != DEF_fifo_enqReq_wires_0_wget_BIT_8___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_enqReq_wires_0_wget_BIT_8___d6, 1u);
	backing.DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 = DEF_fifo_enqReq_wires_0_wget_BIT_8___d6;
      }
      ++num;
      if ((backing.DEF_fifo_enqReq_wires_0_wget____d5) != DEF_fifo_enqReq_wires_0_wget____d5)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_enqReq_wires_0_wget____d5, 9u);
	backing.DEF_fifo_enqReq_wires_0_wget____d5 = DEF_fifo_enqReq_wires_0_wget____d5;
      }
      ++num;
      if ((backing.DEF_fifo_enqReq_wires_0_whas____d4) != DEF_fifo_enqReq_wires_0_whas____d4)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_enqReq_wires_0_whas____d4, 1u);
	backing.DEF_fifo_enqReq_wires_0_whas____d4 = DEF_fifo_enqReq_wires_0_whas____d4;
      }
      ++num;
      if ((backing.DEF_fifo_full__h3124) != DEF_fifo_full__h3124)
      {
	vcd_write_val(sim_hdl, num, DEF_fifo_full__h3124, 1u);
	backing.DEF_fifo_full__h3124 = DEF_fifo_full__h3124;
      }
      ++num;
      if ((backing.DEF_m_input_count_03_EQ_1024___d136) != DEF_m_input_count_03_EQ_1024___d136)
      {
	vcd_write_val(sim_hdl, num, DEF_m_input_count_03_EQ_1024___d136, 1u);
	backing.DEF_m_input_count_03_EQ_1024___d136 = DEF_m_input_count_03_EQ_1024___d136;
      }
      ++num;
      if ((backing.DEF_v__h3759) != DEF_v__h3759)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3759, 32u);
	backing.DEF_v__h3759 = DEF_v__h3759;
      }
      ++num;
      if ((backing.DEF_v__h3839) != DEF_v__h3839)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h3839, 2u);
	backing.DEF_v__h3839 = DEF_v__h3839;
      }
      ++num;
      if ((backing.DEF_v__h4148) != DEF_v__h4148)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4148, 32u);
	backing.DEF_v__h4148 = DEF_v__h4148;
      }
      ++num;
      if ((backing.DEF_v__h4228) != DEF_v__h4228)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4228, 2u);
	backing.DEF_v__h4228 = DEF_v__h4228;
      }
      ++num;
      if ((backing.DEF_v__h4535) != DEF_v__h4535)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4535, 32u);
	backing.DEF_v__h4535 = DEF_v__h4535;
      }
      ++num;
      if ((backing.DEF_v__h4925) != DEF_v__h4925)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4925, 32u);
	backing.DEF_v__h4925 = DEF_v__h4925;
      }
      ++num;
      if ((backing.DEF_v__h5005) != DEF_v__h5005)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h5005, 8u);
	backing.DEF_v__h5005 = DEF_v__h5005;
      }
      ++num;
      if ((backing.DEF_x__h1151) != DEF_x__h1151)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1151, 8u);
	backing.DEF_x__h1151 = DEF_x__h1151;
      }
      ++num;
      if ((backing.DEF_x__h1152) != DEF_x__h1152)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1152, 8u);
	backing.DEF_x__h1152 = DEF_x__h1152;
      }
      ++num;
      if ((backing.DEF_x__h5820) != DEF_x__h5820)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5820, 32u);
	backing.DEF_x__h5820 = DEF_x__h5820;
      }
      ++num;
      if ((backing.DEF_x__h6004) != DEF_x__h6004)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h6004, 8u);
	backing.DEF_x__h6004 = DEF_x__h6004;
      }
      ++num;
      if ((backing.DEF_x__h6070) != DEF_x__h6070)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h6070, 32u);
	backing.DEF_x__h6070 = DEF_x__h6070;
      }
      ++num;
      if ((backing.DEF_x__h6218) != DEF_x__h6218)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h6218, 32u);
	backing.DEF_x__h6218 = DEF_x__h6218;
      }
      ++num;
      if ((backing.DEF_x_wget__h3702) != DEF_x_wget__h3702)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h3702, 2u);
	backing.DEF_x_wget__h3702 = DEF_x_wget__h3702;
      }
      ++num;
      if ((backing.DEF_x_wget__h4091) != DEF_x_wget__h4091)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h4091, 2u);
	backing.DEF_x_wget__h4091 = DEF_x_wget__h4091;
      }
      ++num;
      if ((backing.DEF_x_wget__h4868) != DEF_x_wget__h4868)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h4868, 8u);
	backing.DEF_x_wget__h4868 = DEF_x_wget__h4868;
      }
      ++num;
      if ((backing.DEF_y__h6005) != DEF_y__h6005)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h6005, 8u);
	backing.DEF_y__h6005 = DEF_y__h6005;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_fifo_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_fifo_canonicalize = DEF_CAN_FIRE_RL_fifo_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize = DEF_CAN_FIRE_RL_fifo_deqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize = DEF_CAN_FIRE_RL_fifo_enqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_check_fifos_first, 1u);
      backing.DEF_CAN_FIRE_RL_m_check_fifos_first = DEF_CAN_FIRE_RL_m_check_fifos_first;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_check_fifos_not_empty, 1u);
      backing.DEF_CAN_FIRE_RL_m_check_fifos_not_empty = DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_check_fifos_not_full, 1u);
      backing.DEF_CAN_FIRE_RL_m_check_fifos_not_full = DEF_CAN_FIRE_RL_m_check_fifos_not_full;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_check_outputs, 1u);
      backing.DEF_CAN_FIRE_RL_m_check_outputs = DEF_CAN_FIRE_RL_m_check_outputs;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_cycle_inc, 1u);
      backing.DEF_CAN_FIRE_RL_m_cycle_inc = DEF_CAN_FIRE_RL_m_cycle_inc;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_feed_inputs, 1u);
      backing.DEF_CAN_FIRE_RL_m_feed_inputs = DEF_CAN_FIRE_RL_m_feed_inputs;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_init, 1u);
      backing.DEF_CAN_FIRE_RL_m_init = DEF_CAN_FIRE_RL_m_init;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomA_every, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomA_every = DEF_CAN_FIRE_RL_m_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomA_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomA_every_1 = DEF_CAN_FIRE_RL_m_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomB_every, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomB_every = DEF_CAN_FIRE_RL_m_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomB_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomB_every_1 = DEF_CAN_FIRE_RL_m_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomC_every, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomC_every = DEF_CAN_FIRE_RL_m_randomC_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomC_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomC_every_1 = DEF_CAN_FIRE_RL_m_randomC_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomData_every, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomData_every = DEF_CAN_FIRE_RL_m_randomData_every;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_randomData_every_1, 1u);
      backing.DEF_CAN_FIRE_RL_m_randomData_every_1 = DEF_CAN_FIRE_RL_m_randomData_every_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_m_stop_tb, 1u);
      backing.DEF_CAN_FIRE_RL_m_stop_tb = DEF_CAN_FIRE_RL_m_stop_tb;
      vcd_write_val(sim_hdl, num++, DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28, 1u);
      backing.DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28 = DEF_IF_fifo_deqReq_wires_0_whas__5_THEN_fifo_deqRe_ETC___d28;
      vcd_write_val(sim_hdl, num++, DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19, 8u);
      backing.DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19 = DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d19;
      vcd_write_val(sim_hdl, num++, DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9, 1u);
      backing.DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9 = DEF_IF_fifo_enqReq_wires_0_whas_THEN_fifo_enqReq_w_ETC___d9;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97, 1u);
      backing.DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97 = DEF_IF_m_randomA_zaz_whas__1_THEN_m_randomA_zaz_wg_ETC___d97;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111, 1u);
      backing.DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111 = DEF_IF_m_randomB_zaz_whas__8_THEN_m_randomB_zaz_wg_ETC___d111;
      vcd_write_val(sim_hdl, num++, DEF_NOT_fifo_empty_5___d63, 1u);
      backing.DEF_NOT_fifo_empty_5___d63 = DEF_NOT_fifo_empty_5___d63;
      vcd_write_val(sim_hdl, num++, DEF_NOT_fifo_full_9___d58, 1u);
      backing.DEF_NOT_fifo_full_9___d58 = DEF_NOT_fifo_full_9___d58;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_fifo_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_fifo_canonicalize = DEF_WILL_FIRE_RL_fifo_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize = DEF_WILL_FIRE_RL_fifo_deqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize = DEF_WILL_FIRE_RL_fifo_enqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_check_fifos_first, 1u);
      backing.DEF_WILL_FIRE_RL_m_check_fifos_first = DEF_WILL_FIRE_RL_m_check_fifos_first;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_check_fifos_not_empty, 1u);
      backing.DEF_WILL_FIRE_RL_m_check_fifos_not_empty = DEF_WILL_FIRE_RL_m_check_fifos_not_empty;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_check_fifos_not_full, 1u);
      backing.DEF_WILL_FIRE_RL_m_check_fifos_not_full = DEF_WILL_FIRE_RL_m_check_fifos_not_full;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_check_outputs, 1u);
      backing.DEF_WILL_FIRE_RL_m_check_outputs = DEF_WILL_FIRE_RL_m_check_outputs;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_cycle_inc, 1u);
      backing.DEF_WILL_FIRE_RL_m_cycle_inc = DEF_WILL_FIRE_RL_m_cycle_inc;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_feed_inputs, 1u);
      backing.DEF_WILL_FIRE_RL_m_feed_inputs = DEF_WILL_FIRE_RL_m_feed_inputs;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_init, 1u);
      backing.DEF_WILL_FIRE_RL_m_init = DEF_WILL_FIRE_RL_m_init;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomA_every, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomA_every = DEF_WILL_FIRE_RL_m_randomA_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomA_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomA_every_1 = DEF_WILL_FIRE_RL_m_randomA_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomB_every, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomB_every = DEF_WILL_FIRE_RL_m_randomB_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomB_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomB_every_1 = DEF_WILL_FIRE_RL_m_randomB_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomC_every, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomC_every = DEF_WILL_FIRE_RL_m_randomC_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomC_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomC_every_1 = DEF_WILL_FIRE_RL_m_randomC_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomData_every, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomData_every = DEF_WILL_FIRE_RL_m_randomData_every;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_randomData_every_1, 1u);
      backing.DEF_WILL_FIRE_RL_m_randomData_every_1 = DEF_WILL_FIRE_RL_m_randomData_every_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_m_stop_tb, 1u);
      backing.DEF_WILL_FIRE_RL_m_stop_tb = DEF_WILL_FIRE_RL_m_stop_tb;
      vcd_write_val(sim_hdl, num++, DEF_fifo_deqReq_ehrReg__h1971, 1u);
      backing.DEF_fifo_deqReq_ehrReg__h1971 = DEF_fifo_deqReq_ehrReg__h1971;
      vcd_write_val(sim_hdl, num++, DEF_fifo_deqReq_wires_0_wget____d26, 1u);
      backing.DEF_fifo_deqReq_wires_0_wget____d26 = DEF_fifo_deqReq_wires_0_wget____d26;
      vcd_write_val(sim_hdl, num++, DEF_fifo_deqReq_wires_0_whas____d25, 1u);
      backing.DEF_fifo_deqReq_wires_0_whas____d25 = DEF_fifo_deqReq_wires_0_whas____d25;
      vcd_write_val(sim_hdl, num++, DEF_fifo_empty__h3110, 1u);
      backing.DEF_fifo_empty__h3110 = DEF_fifo_empty__h3110;
      vcd_write_val(sim_hdl, num++, DEF_fifo_enqReq_ehrReg_BIT_8___d8, 1u);
      backing.DEF_fifo_enqReq_ehrReg_BIT_8___d8 = DEF_fifo_enqReq_ehrReg_BIT_8___d8;
      vcd_write_val(sim_hdl, num++, DEF_fifo_enqReq_ehrReg___d7, 9u);
      backing.DEF_fifo_enqReq_ehrReg___d7 = DEF_fifo_enqReq_ehrReg___d7;
      vcd_write_val(sim_hdl, num++, DEF_fifo_enqReq_wires_0_wget_BIT_8___d6, 1u);
      backing.DEF_fifo_enqReq_wires_0_wget_BIT_8___d6 = DEF_fifo_enqReq_wires_0_wget_BIT_8___d6;
      vcd_write_val(sim_hdl, num++, DEF_fifo_enqReq_wires_0_wget____d5, 9u);
      backing.DEF_fifo_enqReq_wires_0_wget____d5 = DEF_fifo_enqReq_wires_0_wget____d5;
      vcd_write_val(sim_hdl, num++, DEF_fifo_enqReq_wires_0_whas____d4, 1u);
      backing.DEF_fifo_enqReq_wires_0_whas____d4 = DEF_fifo_enqReq_wires_0_whas____d4;
      vcd_write_val(sim_hdl, num++, DEF_fifo_full__h3124, 1u);
      backing.DEF_fifo_full__h3124 = DEF_fifo_full__h3124;
      vcd_write_val(sim_hdl, num++, DEF_m_input_count_03_EQ_1024___d136, 1u);
      backing.DEF_m_input_count_03_EQ_1024___d136 = DEF_m_input_count_03_EQ_1024___d136;
      vcd_write_val(sim_hdl, num++, DEF_v__h3759, 32u);
      backing.DEF_v__h3759 = DEF_v__h3759;
      vcd_write_val(sim_hdl, num++, DEF_v__h3839, 2u);
      backing.DEF_v__h3839 = DEF_v__h3839;
      vcd_write_val(sim_hdl, num++, DEF_v__h4148, 32u);
      backing.DEF_v__h4148 = DEF_v__h4148;
      vcd_write_val(sim_hdl, num++, DEF_v__h4228, 2u);
      backing.DEF_v__h4228 = DEF_v__h4228;
      vcd_write_val(sim_hdl, num++, DEF_v__h4535, 32u);
      backing.DEF_v__h4535 = DEF_v__h4535;
      vcd_write_val(sim_hdl, num++, DEF_v__h4925, 32u);
      backing.DEF_v__h4925 = DEF_v__h4925;
      vcd_write_val(sim_hdl, num++, DEF_v__h5005, 8u);
      backing.DEF_v__h5005 = DEF_v__h5005;
      vcd_write_val(sim_hdl, num++, DEF_x__h1151, 8u);
      backing.DEF_x__h1151 = DEF_x__h1151;
      vcd_write_val(sim_hdl, num++, DEF_x__h1152, 8u);
      backing.DEF_x__h1152 = DEF_x__h1152;
      vcd_write_val(sim_hdl, num++, DEF_x__h5820, 32u);
      backing.DEF_x__h5820 = DEF_x__h5820;
      vcd_write_val(sim_hdl, num++, DEF_x__h6004, 8u);
      backing.DEF_x__h6004 = DEF_x__h6004;
      vcd_write_val(sim_hdl, num++, DEF_x__h6070, 32u);
      backing.DEF_x__h6070 = DEF_x__h6070;
      vcd_write_val(sim_hdl, num++, DEF_x__h6218, 32u);
      backing.DEF_x__h6218 = DEF_x__h6218;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h3702, 2u);
      backing.DEF_x_wget__h3702 = DEF_x_wget__h3702;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h4091, 2u);
      backing.DEF_x_wget__h4091 = DEF_x_wget__h4091;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h4868, 8u);
      backing.DEF_x_wget__h4868 = DEF_x_wget__h4868;
      vcd_write_val(sim_hdl, num++, DEF_y__h6005, 8u);
      backing.DEF_y__h6005 = DEF_y__h6005;
    }
}

void MOD_mkTbCFFunctional::vcd_prims(tVCDDumpType dt, MOD_mkTbCFFunctional &backing)
{
  INST_fifo_data_0.dump_VCD(dt, backing.INST_fifo_data_0);
  INST_fifo_data_1.dump_VCD(dt, backing.INST_fifo_data_1);
  INST_fifo_deqReq_ehrReg.dump_VCD(dt, backing.INST_fifo_deqReq_ehrReg);
  INST_fifo_deqReq_ignored_wires_0.dump_VCD(dt, backing.INST_fifo_deqReq_ignored_wires_0);
  INST_fifo_deqReq_ignored_wires_1.dump_VCD(dt, backing.INST_fifo_deqReq_ignored_wires_1);
  INST_fifo_deqReq_virtual_reg_0.dump_VCD(dt, backing.INST_fifo_deqReq_virtual_reg_0);
  INST_fifo_deqReq_virtual_reg_1.dump_VCD(dt, backing.INST_fifo_deqReq_virtual_reg_1);
  INST_fifo_deqReq_wires_0.dump_VCD(dt, backing.INST_fifo_deqReq_wires_0);
  INST_fifo_deqReq_wires_1.dump_VCD(dt, backing.INST_fifo_deqReq_wires_1);
  INST_fifo_empty.dump_VCD(dt, backing.INST_fifo_empty);
  INST_fifo_enqReq_ehrReg.dump_VCD(dt, backing.INST_fifo_enqReq_ehrReg);
  INST_fifo_enqReq_ignored_wires_0.dump_VCD(dt, backing.INST_fifo_enqReq_ignored_wires_0);
  INST_fifo_enqReq_ignored_wires_1.dump_VCD(dt, backing.INST_fifo_enqReq_ignored_wires_1);
  INST_fifo_enqReq_virtual_reg_0.dump_VCD(dt, backing.INST_fifo_enqReq_virtual_reg_0);
  INST_fifo_enqReq_virtual_reg_1.dump_VCD(dt, backing.INST_fifo_enqReq_virtual_reg_1);
  INST_fifo_enqReq_wires_0.dump_VCD(dt, backing.INST_fifo_enqReq_wires_0);
  INST_fifo_enqReq_wires_1.dump_VCD(dt, backing.INST_fifo_enqReq_wires_1);
  INST_fifo_full.dump_VCD(dt, backing.INST_fifo_full);
  INST_m_cycle.dump_VCD(dt, backing.INST_m_cycle);
  INST_m_input_count.dump_VCD(dt, backing.INST_m_input_count);
  INST_m_output_count.dump_VCD(dt, backing.INST_m_output_count);
  INST_m_randomA_ignore.dump_VCD(dt, backing.INST_m_randomA_ignore);
  INST_m_randomA_initialized.dump_VCD(dt, backing.INST_m_randomA_initialized);
  INST_m_randomA_zaz.dump_VCD(dt, backing.INST_m_randomA_zaz);
  INST_m_randomB_ignore.dump_VCD(dt, backing.INST_m_randomB_ignore);
  INST_m_randomB_initialized.dump_VCD(dt, backing.INST_m_randomB_initialized);
  INST_m_randomB_zaz.dump_VCD(dt, backing.INST_m_randomB_zaz);
  INST_m_randomC_ignore.dump_VCD(dt, backing.INST_m_randomC_ignore);
  INST_m_randomC_initialized.dump_VCD(dt, backing.INST_m_randomC_initialized);
  INST_m_randomC_zaz.dump_VCD(dt, backing.INST_m_randomC_zaz);
  INST_m_randomData_ignore.dump_VCD(dt, backing.INST_m_randomData_ignore);
  INST_m_randomData_initialized.dump_VCD(dt, backing.INST_m_randomData_initialized);
  INST_m_randomData_zaz.dump_VCD(dt, backing.INST_m_randomData_zaz);
  INST_m_ref_fifo.dump_VCD(dt, backing.INST_m_ref_fifo);
}
